### ISSUE TITLE
Store integration

### ISSUE THREAD

**Issue by SebastianLuebke** [richardeschloss/nuxt-socket-io#1]
Is a Vuex Store integration planned? vue-socketio and vue-socketio-extended offer that feature

**Comment by richardeschloss** [comment]
Yes, I'm thinking about implementing it and still figuring out how to do it elegantly and the "nuxt way". I was thinking of allowing the user to specify "vuex" options per each socket, and perhaps use glob patterns to define what gets stored. I don't want to constrain the app developer to use specific names for storing. I want the user to have more control. I think it will be far easier to maintain this module that way. 

So, perhaps, the config would be extended like:
```
      { name: 'main', url: 'http://localhost:3000', 
        vuex: [ // 
          { evt: 'downloadProgress', type: {
            progress: Number,
            fmt: 'percentage'
          } }, // Store downloadProgress   
          { evt: 'message[0-9]Rxd' }, //  Store data matching this Regex; i.e., message3Rxd
          { evt: 'user[A-z0-9]+Action' } // Store the matching userX29Action
        ]
      },
```
The idea being here: 

1. Client expects several kinds of events to come from server. It's possible that the client only wants to store a few of those in the global store.
2. It's possible that of the data received, the client may only be interested in subsets of data, and perhaps data fitting a certain type. If the data can be formatted on the fly, it could be one less thing for the app developer to worry about.

But nuxt's own way of dealing with Vuex (with files in the store folder) might be another approach.

I'll toy around with some ideas.

**Comment by richardeschloss** [comment]
@SebastianLuebke 
Update: I just pushed branch [feat/vuex](https://github.com/richardeschloss/nuxt-socket-io/tree/feat/vuex) . This contains the vuex integration. Please see the nuxt.config.js for how I implemented it. The idea is:

1. First configure your state in the store folder.
2. Then in `nuxt.config.js` it's simply a matter of mapping incoming events to the either the vuex mutations or actions. The options can be either an array of strings, or, if there is a mismatch between the server and client, an array of objects mapping the incoming event to vuex can be used. 

I think when it comes to type casting (if ever desired), that would be best suited for the action handlers in the store folder. 

I have tested manually and seems to work. It will take me some time to update my automated tests.

**Comment by richardeschloss** [comment]
Feat/vuex merged.
