### ISSUE TITLE
Prevent polling connection

### ISSUE THREAD

**Issue by 4ndre4s** [richardeschloss/nuxt-socket-io#101]
Hi,

is it possible to prevent polling connections (https://stackoverflow.com/a/28240802/10781526)?

I have the following issues: Sockets disconnect after some time, pressing 'f5' in the browser will fire every event several times.

On my express-server I added `io.set('transports', ['websocket'])`, but this lead to 400 (Bad Request)

**Comment by richardeschloss** [comment]
You'll also want to pass in the transports option on the client. The nuxtSocket plugin will pass down the connect options to the socket.io client.

So this:
```
mounted() {
  this.socket = this.$nuxtSocket({transports: ['websocket'], upgrade: false});
}
```

will be equivalent to this:
```
var socket = io({transports: ['websocket'], upgrade: false});
```

Can you please let me know if that works?

**Comment by 4ndre4s** [comment]
Thank you for your quick response!


This is my mounted hook:
```
mounted () {
      this.socket = this.$nuxtSocket({
        channel: '/' + this.$route.params.id
      })
      this.socket.on('item:add', (item) => {
        this.onAdd(item)
      })
      this.socket.on('item:rename', ({ id, newText }) => {
        this.onItemRename({ id, newText })
      })
    },
```
I tried this.$nuxtSocket({
    channel: '/' + this.$route.params.id,
    transports: ['websocket'], 
    upgrade: false
})

But this did not solve my problems...

**Comment by richardeschloss** [comment]
Ok, just as an FYI..the stackoverflow reference is a bit old, referring to v1.x and may not match the current API docs (see also: [client docs](https://socket.io/docs/client-api/#With-websocket-transport-only) and [server docs](https://socket.io/docs/server-api#new-Server-httpServer-options)). 

So, one key change in socket.io server is that [io.set is gone](https://socket.io/docs/migrating-from-0-9/#io-set-is-gone). So the transport option needs to be provided when starting the IO server:

```
var io = require('socket.io')(server, { transports: ['websocket'] })
```

Also, by default, there is an "allowUpgrades" that defaults to true. You can try setting that to false.

Also, to help isolate the issue, can you please try both on client side:
```
import io from 'socket.io-client'

mounted() {
  const channel = `/${this.$route.params.id}`
  const opts = { transports: ['websocket'], upgrade: false }
  var socket1 = io(channel, opts) // Test with socket.io client directly
  var socket2 = this.$nuxtSocket({ channel, opts }) // Test with plugin

  const testSocket = socket1 // You can toggle this from "socket1" to "socket2"

  // May also wish to try: (per client docs)
  // on reconnection, reset the transports option, as the Websocket
  // connection may have failed (caused by proxy, firewall, browser, ...)
  testSocket.on('reconnect_attempt', () => {
    console.log('do you see me on reconnect attempt?')
    testSocket.io.opts.transports = ['polling', 'websocket'];
  });
}
```

It appears from my testing that the options get passed down, but maybe I'm missing something.

**Comment by 4ndre4s** [comment]
Thank you for your extensive answer! I will try tomorrow and respond then. :)

**Comment by Mark-Brightcloud** [comment]
@4ndre4s did you get it to work eventually?
