### ISSUE TITLE
Improve deployed demo and docs

### ISSUE THREAD

**Issue by richardeschloss** [richardeschloss/nuxt-socket-io#104]
I currently have a branch "heroku" which has updated the chat rooms example to use the new dynamic API feature. That's all working right now here: https://nuxt-socket-io.herokuapp.com/ . 

I think the UI can be improved to better explain what is going on (in the front page and the examples part). The chat rooms example will have a companion article to go with it.

* The demo is technically functional documentation so...an improved demo could potentially be the home of all the docs. The README.md file would just refer people to the hosted docs. That may be more helpful for people, I think.
* I may even want to consider styling the UI to be consistent with nuxtjs.org. This part would just take me some time since I'm not really up to speed with tailwind or exactly how they did things. (if anyone is reading this, a "create-nuxt-docs" would be really useful! It would be just like create-nuxt-app, but would instead create scaffolding for a docs UI !).

**Comment by 8bu** [comment]
Docs are illegible, not explicit. Clean docs will be easier for new user trying to understand how's your plugin works. Type def for typescript user should be implement too. Live demo/example should not be your top priority now

**Comment by richardeschloss** [comment]
Status update: I'm aware of the need for improved docs, I have been on other projects but plan to turn my attention to this in the next two weeks. When in doubt, this repo contains all the working code you need to understand things, including working examples and passing tests. Specific questions can be asked to me in the Nuxt discord. 

What won't be tolerated: bad behavior and disrespect. This project is the result of a lot of effort and thought by very few people, but used by many. At first, the project was tiny, and so the README.md file was simple. As new features got added, the README.md was incrementally updated. Fast forward several months later, the docs grew into what they are today, thus, it is understandable that the docs require there own dedicated space. The README.md on Github makes things a bit difficult to navigate, and that's why this issue was opened. While these particular docs can be improved, I have also written companion articles on [Medium.com](https://medium.com/@richard.e.schloss) which will probably do a much better job at guiding new users. Articles are presented in a series. One follows the other.

If you are someone who gets impatient and frustrated easily, I am someone who can help you, but I also have the choice to help you or not, depending on how you approach me. If you want my help, I'll be glad to, but I require at a minimum, some form of respect and courtesy.

**Comment by richardeschloss** [comment]
https://github.com/nuxt/content/tree/master/docs ... on the roadmap to be repurposed for these docs.

**Comment by richardeschloss** [comment]
Ok, status update (thanks for your patience): the bulk of the work is being done in branch docs/new and a new repo nuxt-socket-io-docs. Still toying with some ideas to make the docs presentable and helpful. Currently what I see on my local machine is pretty awesome, using Nuxt content to make it happen. I think it'll be like a breath of fresh air for anyone who's seen the docs in the past.

**Comment by richardeschloss** [comment]
New docs are hosted now, and much easier to read and navigate, imho: https://nuxt-socket-io.netlify.app/

**Comment by richardeschloss** [comment]
New DOCS live!! I think it'll only get better from here.
