### ISSUE TITLE
 Reconnect doesn't  work.

### ISSUE THREAD

**Issue by shun89** [richardeschloss/nuxt-socket-io#105]
Reconnecting after disconnecting the network cable is invalid.

My code.
`    this.socket = this.$nuxtSocket({
      name: 'home',
      reconnection: true
    })`

**Comment by richardeschloss** [comment]
Hi friend, please also pass in "teardown: false" so that the socket doesn't auto close on disconnect:

``
this.socket = this.$nuxtSocket({ name: 'home', reconnection: true, teardown: false })
```

**Comment by shun89** [comment]
You saved me, thank you so much!
