### ISSUE TITLE
Module no longer works with native modules as of latest version 

### ISSUE THREAD

**Issue by seanCodes** [richardeschloss/nuxt-socket-io#114]
Hi, it looks like the most recent version of the plugin (`1.1.3` that  changes the code to use common js) breaks native module usage. Specifically, an error is thrown when `io.js` uses native module syntax:

```sh
ERROR  Must use import to load ES Module: …/<project>/server/io.js                                                                                                                                                18:12:08
require() of ES modules is not supported.
require() of …/<project>/server/io.js from …/<project>/node_modules/nuxt-socket-io/io/module.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename io.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from …/<project>/server/package.json.
```

This can be reproduced by just adding an `io.js` file with `export default function () { return {}; }`

**Comment by richardeschloss** [comment]
Oh crud, my bad. I had my reasons for reverting it, but was afraid this change was gonna cause issues for people. I think going forward, I'll keep at as an ESM. So I'll revert the change and push soon. Thanks for catching this and I apologize for screwing things up.

**Comment by richardeschloss** [comment]
[v1.1.4](https://www.npmjs.com/package/nuxt-socket-io) pushed. Thanks again for finding this before the week started!

**Comment by seanCodes** [comment]
Thank you!! and thanks for the quick response!
