### ISSUE TITLE
nuxt srcDir incompatible

### ISSUE THREAD

**Issue by sungle3737** [richardeschloss/nuxt-socket-io#116]
i set `nuxt.config.js`

```
module.exports = {
  // Root Directory
  srcDir: 'src/',
  // Meta
  mode: 'universal',
  ...
}
```

so my server directory is src/server/ & page folder in src/page, but nuxt-socket-io doesn't work like this

- io folder in src/server/io.js -> not working
- io folder in server/io.js -> working

I think it should be fixed or directory option should be

**Comment by richardeschloss** [comment]
Hi @sungle3737 , there is an option to specify the io service file in nuxt.config, which should allow you to specify your new location:

nuxt.config:
```js
...
io: {
  server: {
    ioSvc: './src/server/io.js'   // or it may need to be path.resolve(__dirname, '/src/server/io.js'), depending on where you run nuxt from
  }
}
...
```

If the file exists and the module finds it, this should work. However, to help with debugging, if the module can't find the file, it will output an error to the console specifying what file it tried to look for.

See also: [IO Server Overrides documentation](https://nuxt-socket-io.netlify.app/configuration#io-server-overrides). Please let me know if this helps. I have this working in another project, so if it's not working, it's possible we just have slightly different setups.

**Comment by sungle3737** [comment]
```
io: {
  server: {
    ioSvc: './src/server/io'
  }
}
```
this worked, thanks!
