### ISSUE TITLE
Persist option - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sungle3737** [richardeschloss/nuxt-socket-io#118]
### this code works
```
sensor.socket = this.$nuxtSocket({
        name: sensor.name
 })
```

### but this code not works with below error
```
sensor.socket = this.$nuxtSocket({
        name: sensor.name,
        persist: true
})
```
![image](https://user-images.githubusercontent.com/27716524/86561481-b40fec80-bf9b-11ea-8298-ca35206ea3b9.png)

`RangeError: Maximum call stack size exceeded`

- And `nuxt.config.js`
```
sockets: [
      {
        name: 'blabla',
        url: '/blabla',
        nsp: '/blabla'
      }
    ]
```

I can't find the reason of this issue, any mis-setting of mine?

**Comment by richardeschloss** [comment]
Hmm, I'm not entirely sure why that's happening. I have been able to reproduce this, but I'm not sure what the cause of the call stack size being exceeded. I can troubleshoot tomorrow. I think the workaround for now is if persistence is not working, to inject the socket into the root scope:

```js
// Inject into $root scope:
this.$root.sensorSocket = this.$nuxtSocket({
  name: sensor.name,
  // persist: true // Omit for now
})
```

This way you avoid vuex nuances altogether and then in other parts of your code, just use `this.$root.sensorSocket`.

**Comment by richardeschloss** [comment]
I've isolated the problem to the line causing this: 
plugin.js: 
```js
SET_SOCKET(state, { label, socket }) {
  state.sockets[label] = socket // socket is a socket instance, consisting of circular structures, I don't think Vuex likes this.
  // I can set state.sockets to anything and make the error go away. It's only when I set it to the socket instance that the call stack blows up.
},
```

I think injecting into $root scope will be the more reliable way.

**Comment by sungle3737** [comment]
Thanks, but after i route to another page like
```
$router.replace(`/control`)
```

![image](https://user-images.githubusercontent.com/27716524/86577244-e37f2300-bfb4-11ea-986d-532da327408d.png)
the connection unlinked!
sorry for i'm not `socket.io` expert, can't i use same socket in another nuxt page without disconnection?

### use same socket in another nuxt page without disconnection
this is main purpose of this issue

**Comment by richardeschloss** [comment]
You need to pass `teardown: false` as an option if you plan to re-use the socket (also mentioned in #105):

```js
this.$root.sensorSocket = this.$nuxtSocket({
  name: sensor.name,
  teardown: false // <-- add this
  // persist: true // Omit for now
})
```

**Comment by sungle3737** [comment]
wow Thanks, It works!!

**Comment by jacobmolby** [comment]
If you inject $nuxtSocket into the $root is there any way to access it inside of vuex? I can't find on the _this_ context of the action inside vuex, not even when I'm looking at this._vm.

In the vue components it is showing, so I could pass a reference to the action, but I wonder if there is a better way of doing it?

**Comment by richardeschloss** [comment]
Hi @jacobmolby great question! Hmm, I'll look into it now.  For now I'll link to #62, since at one point, committing the socket to Vuex worked. I'm just not sure what changed since then (April 2020) that would have caused this issue.

**Comment by richardeschloss** [comment]
Ok, the quick answer is, the reference will be on `window.$nuxt.$root` inside of the vuex action. I'm 99% confident that will be enough to get you going. Here's what I see on my end:

Suppose I set the socket reference in some page or component: 

```js
this.$root.mySocket = this.$nuxtSocket({
  name: sensor.name,
  teardown: false // <-- add this
  // persist: true // Omit for now
})

// or, as a dummy example
this.$root.dummySocket = 1111 

this.$store.dispatch('someAction')
```

Then in a vuex action, I see this:

```js
actions: {
  someAction(context) {
    console.log(window.$nuxt.$root.mySocket) // Shows in console as socket instance
    console.log(window.$nuxt.$root.dummySocket) // Shows in console as 1111
  }
}
```

While this should work, I'll still keep the issue open to figure out what may have been doing on with the Vuex mutations. Perhaps there is some minor but important configuration in #62 and also my previous demos that allowed it to work. I'll try to get to that later this week.

**Comment by jacobmolby** [comment]
Thanks a lot for the quick reply. 

My 'quick fix' now is I've created a vuex module called socket with an 'emit' action, that takes an object `{evt, msg}`, so that I can use the same API that $nuxtSocket proposes.

If the bug gets fixed I can just change my `dispatch('socket/emit)` to `dispatch('$nuxtSocket/emit)`

**Comment by richardeschloss** [comment]
Can you please share your code (all related state, mutations and actions)?
The dispatch action for emit already exists.

The module tries to persist sockets as an object of label-to-socket pairs.
It sounds like your module is persisting just a single socket, is that
correct?

**Comment by jacobmolby** [comment]
Yes that's true I'm just using a single socket for my application.

_socket.js_
```javascript

export const state = () => ({});

export const actions = {
  //temporary until nuxt socket io "persist" bug is fixed
  emit(_, { evt, msg }) {
    const socket = window.$nuxt.$root.socket;
    socket.emit(evt, msg);
  },
};
```

Example use case
```javascript
this.$store.dispatch('socket/emit', {
        evt: 'LOAD_CHAT',
        msg: { chatId: this.chat._id },
      });
```
Or if we are inside a namespaced vuex module
```javascript
export const actions = {
  async loadChat({ commit, dispatch }, { chatId }) {
    const { chat } = (await ChatService.show(this.$axios, { chatId })).data;

    dispatch(
      'socket/emit',
      {
        evt: 'LOAD_CHAT',
        msg: { chatId },
      },
      { root: true }
    );

    commit('LOAD_CHAT', { chat });
  },
}
```

**Comment by richardeschloss** [comment]
Ok thanks! This helps a lot.

**Comment by richardeschloss** [comment]
Another helpful reference here from Linus Borg: https://forum.vuejs.org/t/vuex-storing-nested-and-circular-structures/20018

**Comment by richardeschloss** [comment]
Also, fwiw...the current $nuxtSocket dispatch action works, since it lets you supply the socket instance:

_io/plugin.js_
```js
  actions: {
    emit(
    { state, commit },
    { label, socket, evt, msg, emitTimeout, noAck } // <-- you can provide your own global socket instance with the current code.  ) {
```

So, the following will work today: 
```js
this.$store.dispatch('$nuxtSocket/emit', {
  socket: window.$nuxt.$root.socket, // plugin will use this. (caveat: I think window is only defined client-side)
  evt: 'LOAD_CHAT',
  msg: { chatId: this.chat._id },
});
```

Nonetheless, I will still work on a fix to have persist option saving to the $root instead of vuex, since circular depenencies are not best stored there (also since reactivity isn't really needed for the socket instances).

**Comment by richardeschloss** [comment]
Ok, I got the fix on my end, with the caveat addressed too. I just need to update the automated tests which will just take a bit of time. I'll try to get the fix released soon. This will be a breaking change only for anyone who has relied on accessing the persisted sockets from vuex store (since now they won't be stored there).

**Comment by richardeschloss** [comment]
Fix released in 1.1.5

**Comment by jacobmolby** [comment]
Oh, thanks! I will definitely do that instead then.

**Comment by jacobmolby** [comment]
Perfect! Thank you very much. I've just updated and it works great.
