### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by sungle3737** [richardeschloss/nuxt-socket-io#119]
My component code
```js
mounted(){
    this.socket = this.$nuxtSocket({ name: 'support' })
},
beforeDestroy(){
    this.socket.disconnect()
}
```

When I create and distroy this component multiple times

![image](https://user-images.githubusercontent.com/27716524/86997537-4a851d80-c1e9-11ea-8b03-8ce598676d47.png)

This issue happens
Well, I can remove this warning by this code
 
```js
require('events').EventEmitter.defaultMaxListeners = 100
```

But I think, even after disconnect all socket, when new new socket connected, new server listener added.
Is there any way to use unique listener for all client socket?
or How can i remove disconnected nuxt socket's listener after disconnection

**Comment by richardeschloss** [comment]
Please read the docs and contributing guidelines before opening issues and please respect the process. It's becoming clear to me you aren't reading the docs which already have answers to your questions. It's starting to irritate me.

**Comment by sungle3737** [comment]
sorry for this
