### ISSUE TITLE
URL not defined when using runtime configuration

### ISSUE THREAD

**Issue by bertramakers** [richardeschloss/nuxt-socket-io#132]
The `nuxt.config.js` of the project I'm working on looks like this:
```
export default {
  [...]
  publicRuntimeConfig: {
    apiKey: process.env.API_KEY,
    apiUrl: process.env.API_URL,
    legacyAppUrl: process.env.LEGACY_APP_URL,
    authUrl: process.env.AUTH_URL,
    newFeaturesUrl: process.env.NEW_FEATURES_URL,
    io: {
      sockets: [
        {
          name: 'uitdatabank',
          url: process.env.SOCKET_URL,
        },
      ],
    }
  },
  io: {
    sockets: [
      {
        default: true,
        name: 'uitdatabank',
      },
    ],
  },
  [...]
}
```

Then, in a component, I have the following code:
```
    mounted() {
      console.log('io', this.$config.io);
      this.socket = this.$nuxtSocket({});
      // ...
   }
```

This results in a warning saying `URL not defined for socket "uitdatabank". Defaulting to "window.location"`:
![Screenshot 2020-08-04 at 16 46 44](https://user-images.githubusercontent.com/959026/89308157-3d394280-d672-11ea-9ded-d4ad00858c14.png)

However, as is visible in the screenshot the URL has been merged into the `io` config as per the documentation: https://nuxt-socket-io.netlify.app/configuration#runtime-configuration

I've tried some variations:
- Adding `url: ''` in the root-level io configuration. Doesn't make a difference.
- Adding a hardcoded `url: 'https://sockets.uitdatabank.dev'` in the root-level io configuration. => This works (see screenshot below)
![Screenshot 2020-08-04 at 16 54 26](https://user-images.githubusercontent.com/959026/89309004-32cb7880-d673-11ea-9f7d-3c4db3db8d18.png)

So the URL is valid and works, but if I put it in the `publicRuntimeConfig` `nuxt-socket-io` doesn't use it for some reason.

We really need this to be configurable at runtime for our project, because we build the app once and then run it with a different `.env` file in different environments with different URLs for the socket server (among other things).

We're using the following versions of nuxt-socket-io and nuxt in our `yarn.lock`:
- [`nuxt-socket-io@^1.1.6`](https://github.com/cultuurnet/udb3-frontend/blob/feature/III-3347-make-nuxt-env-variables-config-at-runtime/yarn.lock#L8333)
- [`nuxt@^2.13.0`](https://github.com/cultuurnet/udb3-frontend/blob/feature/III-3347-make-nuxt-env-variables-config-at-runtime/yarn.lock#L8343)

Can you check if we're doing something wrong, or if this is a bug? I noticed this is a new feature since 7 days.

**Comment by bertramakers** [comment]
Fixed it by changing my config to:
```
export default {
  [...]
  publicRuntimeConfig: {
    apiKey: process.env.API_KEY,
    apiUrl: process.env.API_URL,
    legacyAppUrl: process.env.LEGACY_APP_URL,
    authUrl: process.env.AUTH_URL,
    newFeaturesUrl: process.env.NEW_FEATURES_URL,
    io: {
      sockets: [
        {
          default: true,
          name: 'uitdatabank',
          url: process.env.SOCKET_URL,
        },
      ],
    }
  },
  [...]
}
```
(And leaving out the io config at the root level.)

I was confused by an error in the console that I had to define at least one socket at the root level, but that was on an older version of `nuxt-socket-io` (1.1.4) that didn't support the `publicRuntimeConfig` yet and thus warned that there were no sockets configured (that it knew of).

**Comment by richardeschloss** [comment]
Awesome!
