### ISSUE TITLE
CORS Issues

### ISSUE THREAD

**Issue by erictronics** [richardeschloss/nuxt-socket-io#136]
Hi, can someone help me with how to configure nuxt-socket-io to work with an external domain? I have tried setting origins to * as described in socket.io but still not getting it to work. I want my web application to connect to a socket server on an ESP32 based device. Please, your help will be appreciated

**Comment by richardeschloss** [comment]
I think the answer is here: https://stackoverflow.com/questions/24058157/socket-io-node-js-cross-origin-request-blocked
