### ISSUE TITLE
How to implement this library to newer nuxtjs?

### ISSUE THREAD

**Issue by ombapit** [richardeschloss/nuxt-socket-io#145]
from this library, i see nuxt.config.js has changed from the original installation. and running the dev has also changed. I've followed the tutorial to embed this library into Nuxt, but it hasn't worked. server's socket.io port seems to clash with nuxt. does this library not work with the latest nuxt?

**Comment by richardeschloss** [comment]
It works with nuxt 2.14. (latest stable release). Can you please try forking this repo and running `npm run dev` script to see how far you can get? (but makes sure to `npm install nuxt` after forking/cloning the repo). The demo app should work at localhost:3000 with some very basic examples.

**Comment by ombapit** [comment]
oh i think,i generate nuxt project with internal nuxt server. i'll try to creating new project using express. i'll inform later.

**Comment by richardeschloss** [comment]
v1.1.11 will have the updated dependencies.
