### ISSUE TITLE
Can't set ws:// protocol as default

### ISSUE THREAD

**Issue by scoutrul** [richardeschloss/nuxt-socket-io#151]
Hello, Richard!

I just found a small issue:
I need connect via wss:// protocol, but plugin connects to https instead, even if module set like:
`      io: {
    sockets: [
      {
        name: "supportChat",
        default: true,
        url: "wss://....io/api"
      }
    ]
  }
`

The workaround is to set URL default  to "" (empty) and hardcode protocol in mount section like this

`    this.socket = this.$nuxtSocket({
      channel: 'index',
      path: "wss://....io/api"
    });`

Maybe, I miss something in the docs, but I can’t find any tips how to set the protocol by default.

**Comment by richardeschloss** [comment]
To do what you want, you may want to consider the transports option "websockets". (see also: https://socket.io/docs/client-api/#With-websocket-transport-only)

```js
this.socket = this.$nuxtSocket({ transports: ['websocket']});
```

I don't think your connection url would include the "wss", I think the socket.io library (underneath) will handle that protocol for you when specifying "transports". Please let me know how far you get. 

The reason your workaround works is that when url is empty, `window.location` is used instead to connect:

**Comment by scoutrul** [comment]
Thank you, the transports option did make sense!
