### ISSUE TITLE
Router replace not working

### ISSUE THREAD

**Issue by Fendry02** [richardeschloss/nuxt-socket-io#152]
Hi everybody ! 

I'm facing a weird issue regarding router replacement and nuxt socket io. 
I have a router in a beforeCreate that just replace the route as this on /admin/recipes: 

`  beforeCreate() {
    this.$router.replace({ path: '/admin/recipes/upcoming' })
  },
`

And then in /admin/recipes/upcoming, I am using nuxtsocket like this:

`
  mounted() {
    this.socket = this.$nuxtSocket({
      name: 'admin',
      channel: '/admin',
    })
`

The issue is, when I drirectly go to /admin/recipes/upcoming, everything is working but when I go to /admin/recipes, I receive a large amount of error ! (about 20 000..), the first one is about eventNative:

`Property or method "nativeEvent" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.`

Then 

`Property or method "preventDefault" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property`

For information:
nuxt-socket-io: 1.1.11
nuxt: 2.14.6

Thank you !
Regards

**Comment by richardeschloss** [comment]
I can't reproduce this error and it looks like from the provided error messages, the issue is beyond the scope of the nuxt-socket-io module.
