### ISSUE TITLE
Enhancement: Types for plugin and module

### ISSUE THREAD

**Issue by richardeschloss** [richardeschloss/nuxt-socket-io#153]
I think having either a types definition file or JSDoc comments would make the plugin easier to use, especially in VS code where Intellisense will show what arguments/types are possible. This may help save users a trip to the docs.

**Comment by richardeschloss** [comment]
Nvm. The plugin is dynamically injected, making it difficult to get the benefit of typing and vscode intellisense :(. This turned out to be more challenging than I thought

**Comment by wkillerud** [comment]
I've added some types locally to my current Nuxt-project using TypeScript and nuxt-socket-io. They only cover the absolute basics, so they may or may not be of help to you or anyone finding this. But, they let you find `this.$nuxtSocket({})` in your components. I inlined the option documentation do, as you say, help save users a trip to the docs.

```typescript
import * as SocketIOClient from 'socket.io-client';

interface NuxtSocketOpts extends SocketIOClient.ConnectOpts {
  /** Name of the socket. If omitted, the default socket will be used. */
  name?: string;
  /** The channel (a.k.a namespace) to connect to. Defaults to ''. */
  channel?: string;
  /** Specifies whether to enable or disable the "auto-teardown" feature (see section below). Defaults to true. */
  teardown?: boolean;
  /** Specifies whether to save this socket in Vuex (see [vuexModule](https://nuxt-socket-io.netlify.app/vuexModule)). */
  persist?: boolean;
  /** Specifies the property in [this] component that will be used to contain the socket status. Defaults to 'socketStatus' (referring to an object). */
  statusProp?: string;
  /** Specifies the timeout in milliseconds for an emit event, after which waiting for the emit response will be canceled. Defaults to undefined. */
  emitTimeout?: number;
  /** Specifies the property in [this] component that will be used to contain emit errors (see section below). Defaults to 'emitErrors' (referring to this.emitErrors, an object of arrays). */
  emitErrorsProp?: string;
}

export interface NuxtSocket extends SocketIOClient.Socket {}

declare module 'vue/types/vue' {
  interface Vue {
    $nuxtSocket: (ioOpts: NuxtSocketOpts) => SocketIOClient.Socket;
  }
}

declare module '@nuxt/types' {
  interface Context {
    $nuxtSocket: (ioOpts: NuxtSocketOpts) => SocketIOClient.Socket;
  }
}
```

And a usage example:

```typescript
import Vue from 'vue';
import { NuxtSocket } from '~/types/vue-nuxt__socket-io';

export default Vue.extend({
  data() {
    return {
      message: '',
      socket: null as NuxtSocket | null,
      socketStatus: {},
    };
  },

  mounted(): void {
    this.socket = this.$nuxtSocket({});
    this.socket.on('connect', () => {
      if (!this.socket) {
        return;
      }
      console.log('🚀');
    });
  },
});
```

**Comment by richardeschloss** [comment]
Hi, yes, this will be very helpful for Typescript users.

**Comment by richardeschloss** [comment]
Update. I started work on this..I was able to get the global types work. (I wanted to make sure things would still work when the types are in the node_modules subdir, which I was afraid was going to be ignored). I should have a PR later today on this.

**Comment by richardeschloss** [comment]
I was able to get most of this working. My only snag right now is trying to work with the extended properties. For example:

```js
this.socket = this.$nuxtSocket({
  /* Nuxt socket opts */
  channel: '/someStr', // ok  

  /* Remaining opts (SocketIOClient.ConnectOpts) */
  reconnection: false // VS code gives an error, but it is, however, a valid prop
})
```

**Comment by richardeschloss** [comment]
I just pushed branch [feat/types](https://github.com/richardeschloss/nuxt-socket-io/tree/feat/types). If considering submitting a PR, it will be best to submit to that branch now instead of development. It mostly works except it just needs to have the following:
1. types for the other supported props in [plugin.js](https://github.com/richardeschloss/nuxt-socket-io/blob/feat/types/io/plugin.js#L788)
2. If possible, support for the extended options, such as ["reconnection"](https://github.com/richardeschloss/nuxt-socket-io/blob/feat/types/components/Messages.vue#L74). On my machine, VS code errors out and I have to ts-ignore it (which isn't too big of deal for me, but may be for others)
3. It may be useful to also define the types for moduleOptions (which are very similar to the plugin options). This way, people can get intellisense in the nuxt config.

**Comment by wkillerud** [comment]
Regarding the extended options such as `reconnection`: I forgot, you need to install `@types/socket.io-client` since `socket.io-client` does not ship its own types for us to extend. I guess it can be added as a dependency here? I'll see what I can do about the rest :)

**Comment by richardeschloss** [comment]
Perhaps "@types/socket.io-client" as a development dependency in package.json.
