### ISSUE TITLE
Listen to all events

### ISSUE THREAD

**Issue by marahmanjs** [richardeschloss/nuxt-socket-io#154]
is it possible to listen to all events from  server as

`socket.on('*' , (resp) =>{
   console.log("resp " , resp)
}`

**Comment by richardeschloss** [comment]
Yes, it's currently possible with a separate plugin: [socketio-wildcard](https://github.com/hden/socketio-wildcard). The wildcard plugin however is not currently integrated into nuxt-socket-io. I will consider integrating it when that project becomes more stable. At 184k downloads/month, however, it seems to satisfy the needs of most users.
