### ISSUE TITLE
Reconnecting all the time with status 101 Switching Protocols 

### ISSUE THREAD

**Issue by Feduch** [richardeschloss/nuxt-socket-io#156]
Hi! 

Thank you very much for this project.

I try to use this in my project. On the back (aws websocket gateway api) lambda function is triggered on connected, but connection not establishing.

nuxt.config.js

`
io: {
    sockets: [{
      name: "statistics",
      url: "wss://***.us-east-1.amazonaws.com"
    }]
  },
`

`mounted() {
      this.socket = this.$nuxtSocket({path: "/development", transports: ["websocket"]})
}`

Where am I going wrong?

![DeepinScreenshot_выберите-область_20201025090300](https://user-images.githubusercontent.com/5888590/97100198-ec9a1a00-16a1-11eb-9824-dd9d11c3cde4.png)

**Comment by richardeschloss** [comment]
Just specify reconnection to "false". Socket.io client under the hood by default tries to auto reconnect.

**Comment by kamerat** [comment]
Is `transports: ["websocket"]` required to establish a websockets connection? Shouldn't it automatically upgrade to ws?
I have the same problem.

### server.js
```js
const express = require('express')
const app = express()
const server = require('http').Server(app)
const io = require('socket.io')(server, {name: 'main'})

io.on('connection', socket => {
    console.log('connection', socket)
    socket.on('testa', (emit) => {
        console.log(emit);
    })

})

server.listen(3001)
```

### nuxt.config.js
```js
modules: [
    'nuxt-socket-io',
],

io: {
    // module options
    sockets: [{
        name: 'main',
        url: 'http://localhost:3001',
    }]
},
```

### index.js
```js
mounted() {
    this.socket = this.$nuxtSocket({})
}
```

With the mounted above, it only uses polling, it never upgrades. However, If i do this instead:

```js
mounted() {
    this.socket = this.$nuxtSocket({transports: ["websocket"]})
}
```

It successfully connects to my socket using websocket.

**Comment by Feduch** [comment]
@kamerat  Can you try it with  server on AWS API Gateway Websocket?

**Comment by kamerat** [comment]
I ended up using vue-socket.io as a custom nuxt plugin.

**Comment by richardeschloss** [comment]
Hopefully these links help you troubleshoot your specific issue:
- https://socket.io/docs/v3/troubleshooting-connection-issues/
- https://socket.io/docs/v3/client-api/#new-Manager-url-options --> it seems like the auto upgrade should happen (`upgrade` defaults to true). There is also a `rememberUpgrade` option you may wish to set to true.
