### ISSUE TITLE
this.socket.emit does not seem to be working after initializing this.socket = this.$nuxtSocket().. 

### ISSUE THREAD

**Issue by Mark-Brightcloud** [richardeschloss/nuxt-socket-io#160]
client:
in mounted() 

```
 this.socket = this.$nuxtSocket({
      channel: '/chat',
      transports: ['websocket'],
      upgrade: false,
      reconnection: true
});
```
then I have 
```
socket.emit('message', {                                <------ client ws messages does not show any message sent
      hello: 'world' 
    }, (resp) => {
      console.log('resp', resp);
})
```
server:
```
io.of('chat').on('connect', (socket) => {
  console.log('IO connected:', socket.id)         <----- this works 
  socket.emit('news', { hello: 'world' });            <------ this works too, client receive the message upon connection
  socket.on('message', function(msg){         
    console.log('msg', msg)                              <------ server does not print any message
  })
})
```
server does not get any message. initial IO works, but the second part of emitting message from client to server not working, please help :)

**Comment by richardeschloss** [comment]
I think "socket.emit" should be "this.socket.emit" ?

**Comment by richardeschloss** [comment]
Here's the most basic example that currently works: [Messages](https://github.com/richardeschloss/nuxt-socket-io/blob/324099b13f2e3b7d4db19bab6a82d121ac2a636f/components/Messages.vue#L79) . 

My advice is to try matching that example first and then seeing what minor differences / options cause it to break.

**Comment by Mark-Brightcloud** [comment]
thanks for the fast reply! "this.socket.emit" didn't work either. I have a pretty simple setup. 

`this.socket = this.$nuxtSocket` works in mounted(). but any action called on this.socket.emit()  does nothing. very frustrated...

**Comment by Mark-Brightcloud** [comment]
only part that works so far is

client:
```
this.socket = this.$nuxtSocket({
      channel: '/chat',
      transports: [ 'websocket' ],
      reconnection: false
});
```

server:
```
io.of('chat').on('connect', (socket) => {
  console.log('IO connected:', socket.id)
  socket.emit('b', 'hi from server');
})
```

**Comment by Mark-Brightcloud** [comment]
do i have to have vuex setup for this to work?

**Comment by richardeschloss** [comment]
No need to have vuex setup, but my guess is it's perhaps the server setup that's broken, not the client-side. Please see the examples in this repo to see how it's done.

**Comment by colodenn** [comment]
Not working for me either.

**Comment by richardeschloss** [comment]
This git repo has the working examples. Tested with the latest version of nuxt-socket-io.  Using express on the backend. 

> Here's the most basic example that currently works: [Messages](https://github.com/richardeschloss/nuxt-socket-io/blob/324099b13f2e3b7d4db19bab6a82d121ac2a636f/components/Messages.vue#L79) .
> 
> My advice is to try matching that example first and then seeing what minor differences / options cause it to break.

By matching, I mean, please clone the repo (with known working code), and then work to see what differences cause it to break.
