### ISSUE TITLE
disconnect event listener not triggered on socket disconnect

### ISSUE THREAD

**Issue by Syntle** [richardeschloss/nuxt-socket-io#162]
I am trying to listen to socket disconnections but it won't work, on the other hand, the `connect` event is always fired when a socket connects.

I don't use any options when creating the `$nuxtSocket` (`this.socket = this.$nuxtSocket({})`)

I have tried the following:
- `this.socket.on('disconnect', () => console.log('socket disconnected!')` in page files inside the `mounted()`/`watch` hooks.
- `socket.on('disconnect', () => console.log('socket disconnected!')` in the `server/io.js` file inside a function.

in both cases, nothing is fired, **unless** I terminate the nuxt process from the terminal while the socket is still connected.

Please note, when a socket connects/disconnects `nuxt-socket-io` does log that in the terminal as shown here:
![image](https://user-images.githubusercontent.com/43820255/99177943-41134100-2706-11eb-807a-e6f26a116b46.png)

Edit:
I have tested this with Firefox and the listener is only triggered if I refresh/close the page but:
```js
this.socket.on('disconnect', () => {
  console.log('testing disconnect event') // Runs
  this.socket.emit('disconnectTest') // Isn't running
})
```

**Comment by richardeschloss** [comment]
Please provide the following clarification: do you want your client side to know when the socket IO server has disconnected, or do you want to know when other socket IO clients have disconnected?

**Comment by Syntle** [comment]
I want to know when a socket client has disconnected.

**Comment by richardeschloss** [comment]
this.socket.on('disconnect', () => {
  console.log('testing disconnect event') // Runs
  this.socket.emit('disconnectTest') // Isn't running  --> Correct: this shouldn't be sent after the disconnect.
})

**Comment by Syntle** [comment]
Oh, my bad then.

Is it possible to setup event listeners in the socket server? I want to make sure the socket server knows when a socket client disconnects.

**Comment by richardeschloss** [comment]
If you want to know when the client has disconnected, the socket.on('disconnect') event handler should work, because it *is* working here: 

https://github.com/richardeschloss/nuxt-socket-io/blob/324099b13f2e3b7d4db19bab6a82d121ac2a636f/io/module.js#L115

```js
   socket.on('disconnect', () => {
      consola.info('client disconnected from', namespace)
    })
```

This line produces that error message you're seeing. So the exact code should work

**Comment by Syntle** [comment]
Would you mind telling me how I'd go about listening to events in the socket server? As far as I know, you're only able to create functions that are essentially emit-listeners.

**Comment by richardeschloss** [comment]
Inside `server/io.js`, you should be able to listen to it like this:

```js
export function Svc(socket, io) {
  socket.on('disconnect', (reason) => {
    console.log('disconnect occurred!', reason)  
  })
  return Object.freeze({}) // Placeholder
}
```

**Comment by Syntle** [comment]
I understand now, thank you for explaining it to me and thank you for your very quick responses!
