### ISSUE TITLE
emitting to specific rooms isn't working

### ISSUE THREAD

**Issue by Syntle** [richardeschloss/nuxt-socket-io#163]
I tried using `io.in(room.id).emit('messageReceive', { msg: message })` to emit to sockets connected to a specific room but the listeners are not getting triggered they only get triggered when I emit to all connected sockets (`io.emit()`)

The sockets are joined to the rooms in another function like so:
```js
const user1sckt = io.of('/').connected[user1.socketID]
const user2sckt = io.of('/').connected[user2.socketID]
user1sckt.join(id)
user2sckt.join(id)
```

**Comment by richardeschloss** [comment]
Please refer to these docs: https://socket.io/docs/v3/rooms/index.html to accomplish this.
