### ISSUE TITLE
How to use socketio in express with nuxtjs?

### ISSUE THREAD

**Issue by colodenn** [richardeschloss/nuxt-socket-io#164]
When I try to connect to this socket endpoint my nuxtjs applications errors saying cors aren't allowed.

```node
const app = require('express')()
var cors = require('cors')
var http = require('http').createServer(app)

var io = require('socket.io')(http, {
  cors: {
    origin: "http://localhost:1337",
    methods: ["GET", "POST"]
  }
});

app.get('/', (req, res) => {
  res.send('Hello World!');
});

io.on('connection', (socket) => {
  console.log('a user connected');
});

http.listen(1337, () => {
  console.log('listening on *:1337');
});

```
`Access to XMLHttpRequest at 'http://localhost:1337/socket.io/?EIO=3&transport=polling&t=NNIP7Zz' from origin 'http://localhost:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by richardeschloss** [comment]
Please consider reading the docs before opening issues. Thanks.
