### ISSUE TITLE
Upgrade SocketIO dependancy to v3

### ISSUE THREAD

**Issue by anselmpaul** [richardeschloss/nuxt-socket-io#167]
I struggled setting up a simple demo with a socketIO server running on `localhost:3001` and my nuxt-socket-io running on `localhost:3000` because of some CORS issues. Turns out (the relatively new) v3 of socketIO has CORS issues with the v2.3 (see https://github.com/socketio/socket.io-client/issues/1140#issuecomment-728840985). For now I have downgraded my socketIO backend to v2.3 but I suggest updating your dependancy might prevent future problems. Cheers!

**Comment by richardeschloss** [comment]
Hi, good find. My question is: if v3 is the one with CORS issues, don't you want to hold the dependencies to 2.3 until 3.x becomes more stable?

**Comment by anselmpaul** [comment]
Valid point. I've asked the maintainer of socket.io if this is considered a breaking change between v2.3 and v3.0 or a bug. 
(See https://github.com/socketio/socket.io-client/issues/1390#issuecomment-733607323)

**Comment by richardeschloss** [comment]
Status update: waiting for socket.io v3 to become more stable before updating this. Users are still free to update socket.io as they wish to v3 and have at it.

**Comment by richardeschloss** [comment]
FYI for CORS issues: https://github.com/socketio/socket.io-client/issues/1140#issuecomment-733765724

**Comment by larzon83** [comment]
Stable enough now? :)
I updated socket.io and socket.io-client both to 3.1.0 in my project and also adjusted cors on my server to new v3 way. Everything works smoothly...

**Comment by richardeschloss** [comment]
I'll test this week and try to get this closed soon.

**Comment by richardeschloss** [comment]
1.1.14 coming soon.
