### ISSUE TITLE
Feature request: Option for deactivating console.info from connectSocket function

### ISSUE THREAD

**Issue by ArticSeths** [richardeschloss/nuxt-socket-io#168]
Hello, I am looking for how to deactivate the console warnings when connecting to a socket, I am seeing that directly from the function there is no parameter to deactivate this.

I am talking about the following function:
function connectSocket() {

**Comment by richardeschloss** [comment]
Currently, there is only an option to disable/enable console.warn, not console.info. The way to currently hide the info messages is to uncheck the log level "info" in the logger that you're using. If I recall correctly, think I chose this design to prevent users from opening issues on "not seeing the connection" or similar. 

However, I'll keep this issue open and may consider adding the option in (default to enabled), as it is fairly simple to implement. My suggested change for the time being would be something like this: 

```js
  const { sockets, warnings = true, infoMsgs = true } = mergedOpts
  
  warn =
    warnings && process.env.NODE_ENV !== 'production' ? console.warn : () => {}

 info =
    infoMsgs && process.env.NODE_ENV !== 'production' ? console.info : () => {}

```

And then the two statements that use "console.info" would be replaced by "info".  

Alternatively, perhaps "logLevel" would be more appropriate, but that may break code that is currently using the "warn" option.

**Comment by ArticSeths** [comment]
Okay, i have made this #170 . Take a look!

**Comment by richardeschloss** [comment]
Thanks! Merged. Appreciated!

**Comment by richardeschloss** [comment]
1.1.3 released.
