### ISSUE TITLE
Nuxt composition API

### ISSUE THREAD

**Issue by PMLS3** [richardeschloss/nuxt-socket-io#169]
is nuxt-socket-io compatible with the composition api? 

I keep getting an config error when I try to initiate: cannot read property of "$config" of undefined. 

Thank you in advance

**Comment by richardeschloss** [comment]
I've never tried using the Nuxt composition API and I apologize that I'm not really familiar with that. Is that fairly new? I'd be interested to still learn it.. 

My guess as to what might be throwing the error may be the treatment of the context. In nuxt-socket-io/plugin.js, "$config" is pulled from `this`:
https://github.com/richardeschloss/nuxt-socket-io/blob/324099b13f2e3b7d4db19bab6a82d121ac2a636f/io/plugin.js#L807

Is that the line where you encounter the error, or is it someplace else where `this.$config` or `[some undefined var].$config` is being used?

**Comment by PMLS3** [comment]
Yes I agree, with VUE 3 being a big hit I'm sure that the Nuxt Composition API will become a permanent feature. 

I have a test video chat here where I tried the composition api on the composition page https://github.com/PMLS3/nuxt-video-chat.git 

I used PeerJS in conjunction which works 90% of the time and the other times doesn't register and no UI so don't judge :)

**Comment by richardeschloss** [comment]
A potential problem I see could be during destructuring of the context properties, so that calling $nuxtSocket on it's own loses the context the plugin was expecting. 

What happens if you don't destructure? 

```js
const ctx = useContext(); // If this is Nuxt context, it should contain $config as a property.
const socket = ctx.$nuxtSocket({ channel: "/videochat" }); // Does our original error message go away or at least become something new?
```

**Comment by PMLS3** [comment]
Cannot read property 'state' of undefined --> getting this 

I'll let you know if I can get a workaround with it...

**Comment by richardeschloss** [comment]
Ok I'm glad to see progress. The plugin pulls state from `this.$store`, so if $store no longer exists on context, it looks like it's store now? So, I'm guessing a workaround could be `ctx.$store = ctx.store`

**Comment by richardeschloss** [comment]
Haven't received any response on this so I'm closing this for now.

**Comment by richardeschloss** [comment]
Discussion continues on #187
