### ISSUE TITLE
I installed it into my existing nuxt app but doesn't work.

### ISSUE THREAD

**Issue by EriniKarpadaki** [richardeschloss/nuxt-socket-io#174]
Hi, I installed nuxt-socket-io and tried to make it work with some basic functionalites but it didn't work.
Below are my tries.
![image](https://user-images.githubusercontent.com/69481913/100983229-b62da580-3551-11eb-8e17-f01df68ccf6b.png)
![image](https://user-images.githubusercontent.com/69481913/100983353-e1b09000-3551-11eb-88da-edf1aa180fa0.png)
![image](https://user-images.githubusercontent.com/69481913/100983447-01e04f00-3552-11eb-84f9-1566cf756401.png)

Is there any required options I didn't configure?
Is there some problem with my socket server?
Your package is very useful for my project. I tried several times but still not overcome.
Would you please help me with it. 
Thanks in advance.

**Comment by richardeschloss** [comment]
I think your socket url needs to be a full url to work? Not just a relative path.

**Comment by richardeschloss** [comment]
Haven't received any response on this so I'm closing.
