### ISSUE TITLE
data is not receiving from nuxt-socket-io

### ISSUE THREAD

**Issue by David-fang0621** [richardeschloss/nuxt-socket-io#180]
This is my component to be used.
mounted() {
    this.socket = this.$nuxtSocket({
      transports: ['websocket']
    })
    this.socket.emit('echo', {text: "hello world"}, function(response)  {
      console.log(response)
    })
  },

This is my nuxt.config.js
modules: [
    'nuxt-svg-loader',
    'nuxt-socket-io',
  ],

  io: {
    // module options
    sockets: [{
      name: 'main',
      url: 'ws://xx.xx.xx.xx:9999'
    }]
  },
It's no result, but it's working with javascript.
![2021-01-24_07h04_58](https://user-images.githubusercontent.com/59463548/105616525-b68c4380-5e12-11eb-9a66-c5780f65291e.png)

What am I wrong?

**Comment by richardeschloss** [comment]
As a courtesy to me and other readers, please format your code snippets by surrounding them with three tick marks (```) and indenting the blocks.

What happens when you try with the newest socket.io 3.x ? The latest nuxt-socket-io now uses 3.x.

**Comment by richardeschloss** [comment]
Closing for now.

**Comment by David-fang0621** [comment]
Sorry for the late reply. I have uploaded the code snippet via code sandbox.

https://codesandbox.io/s/cranky-meadow-21z6j?file=/pages/socket.vue
