### ISSUE TITLE
How do I access the socket.io server instance?

### ISSUE THREAD

**Issue by Worie** [richardeschloss/nuxt-socket-io#183]
Hello! Thanks for the great package :)

I believe I lack a thing or two in my understanding of that. The thing is that I want to reuse the already created socket.io server to emit events from server to clients when something happens (i.e. - db gets updated, endpoint gets called)

I've tried to use nuxt `serverMiddleware` to achieve that but none of the solutions worked as I would expect and I don't feel that is the right way to do so.

So the question is: How do I access the socket.io server instance created by the module from within servermiddleware? Is that possible at all? I need to broadcast images to all connected clients and create custom rules there.

Thanks in advance ✌️

**Comment by richardeschloss** [comment]
It's actually easiest to just create the folder structure and let the module work for you (see also: https://nuxt-socket-io.netlify.app/configuration#automatic-io-server-registration). 

In the most simplest example, you would create a file: [appRoot]/server/io.js . nuxt-socket-io will see that file and use it when you start your app.

In that file you just need the following:

```js
export default function(socket, io) {
  // Here, nuxt-socket-io will call this function when socket.io-client connects to "/"
  // and will give you the socket and io (server instance)
  // socket.emit('someEvt', { msg: 123 }) // <-- so you can socket.emit here. this would go back to client
  // socket.on('fromClient', (msg) => { /* handle msg */ }) // this would come from client
  return Object.freeze({})
}
```

As yet another convenience, you could re-write part of that above snippet like this:

```js
export default function(socket, io) {
  return Object.freeze({
    fromClient (msg) { <-- when io server receives "fromClient", this function gets called.
     /* handle msg */
     return { resp: 'got it' }
   }
  })
}
```
I personally think the second snippet is easier to write, but that comes down to personal preference (it's merely my opinion, not a fact). I give users the choice which way they want to write it.
