### ISSUE TITLE
Help with basic websocket example

### ISSUE THREAD

**Issue by TheFoolishPupil** [richardeschloss/nuxt-socket-io#186]
# Help with a basic Websocket example 🙃
Hey there! I'm relatively new to Nuxt as well as Websockets. I have a minimal use case that I have working in a react client that I am trying to implement in a Nuxt project. I have tried following along the documentation as well as basic examples but seem to lack understanding of how I should approach my problem. 

Simply put, I want to display live json data from a websocket in one of my nuxt components.
## WebSocket Server
I have the following server that broadcasts incoming data from to connected clients:
```javascript
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 3030 });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(data) {
    wss.clients.forEach(function each(client) {
      // Use this whwen receiving data from external client
      // if (client !== ws && client.readyState === WebSocket.OPEN) {
      if (client.readyState === WebSocket.OPEN) {
        client.send(data);
      }
    });
  });
});
```

## Client
I previously used the native WebSocket object to receive data on my front end with:
```javascript
let ws = new WebSocket(URL);

ws.onopen = () => {
  console.log('connected');
}

ws.onmessage = evt => {
  const message = JSON.parse(evt.data);
  setMessages(messages => ({ ...messages, [message.ip]: message }));
}

ws.onclose = () => {
  console.log('disconnected');
  ws = new WebSocket(URL);
}

return function cleanup() {
  ws.close()
}
```
When I attempt to use this code in my Nuxt component the error `WebSocket is not defined is generated`. Which has in turn brought me to this plugin. Any help with implementing this simple use case would be much appreciated.

Thanks!!

**Comment by richardeschloss** [comment]
Hi, this link might help: [What-Socket-IO-is-not](https://socket.io/docs/v3/index.html#What-Socket-IO-is-not)

So, the main thing to note is while Socket.io *uses* websocket, it is not a websocket implementation.

**Comment by TheFoolishPupil** [comment]
Hey Richard. Thanks for the response. This was precisely the misconception I held about socket io. After looking at its documentation and have a more correct understanding now. Have working communication between my Nuxt app and a socket io server now so I'm happy. 

Cheers
