### ISSUE TITLE
Nuxt composition API (stable state)

### ISSUE THREAD

**Issue by udisun** [richardeschloss/nuxt-socket-io#187]
in composition-api there is no `this`, instead in the setup function we can get the closest to `this` object from `context.app`
```javascript const { app: { $axios, $cookies, $nuxtSocket, store } } = context```
one of the issues is that `$store` has been renamed to `store` inside `app`, so to solve this we bind the `$nuxtSocket` like so:
```javascript
onMounted(() => {
      const boundNuxtSocket = $nuxtSocket.bind({ ...app, $store: store })
      socket.value = boundNuxtSocket({
        // nuxt-socket-io opts:
        name: 'main',

        // socket.io-client opts:
        reconnection: true,
      })
    })
```

still after doing all that we get errors:

![error from store](https://user-images.githubusercontent.com/950100/112862020-06f77a00-90be-11eb-9ee9-9c334b82c5d9.png)

Looking into that it seems these are the lines in question:
```javascript
teardown({ ctx, socket, useSocket }) {
    if (ctx.onComponentDestroy === undefined) {
      ctx.onComponentDestroy = ctx.$destroy
    }

    ctx.$on('closeSockets', function() {
      socket.removeAllListeners()
      socket.close()
    })
```

ctx is seemed to be `this` meaning our `app` when looking what calls `teardown`:

```javascript
if (teardown) {
    register.teardown({
      ctx: this,
      socket,
      useSocket
    })
  }
```

and this is what's inside of `app` or `this` for $nuxtSocket:
![app object](https://user-images.githubusercontent.com/950100/112862893-ea0f7680-90be-11eb-9a41-c21b490566d8.png)

current workaround is to pass to the $nuxtSocket options:
`teardown: false`
but then we miss out on that and need to implement teardown functionality ourselves.

so I'm not sure who/what is supposed to add `$on` to `this` object but that doesn't happen.

please help

**Comment by richardeschloss** [comment]
I think you want [useContext](https://composition-api.nuxtjs.org/helpers/useContext) in your setup function. Let me know how far you get with that. I'm not that familiar with the composition api, but I'm thinking something like:

```js
setup() {
  const ctx = useContext()
  ctx.mySocket = ctx.$nuxtSocket({...})
},
```

All the "this" references inside of nuxt socket would rely on that context.

**Comment by udisun** [comment]
> I think you want [useContext](https://composition-api.nuxtjs.org/helpers/useContext) in your setup function. Let me know how far you get with that. I'm not that familiar with the composition api, but I'm thinking something like:
> 
> ```js
> setup() {
>   const ctx = useContext()
>   ctx.mySocket = ctx.$nuxtSocket({...})
> },
> ```
> 
> All the "this" references inside of nuxt socket would rely on that context.

I am using context, as I've written, inside the context object there is an app object and inside it what you expect as `this` in a options interface based component.
`const { app: { $axios, $cookies, $nuxtSocket, store } } = context`
context here is a variable created from:
`const context = useContext()`

so this is not related to the issue I've mentioned.

**Comment by richardeschloss** [comment]
Ok, i've just been using the composition api. Everything works fine if the nuxtSocket is instantiated in the mounted() hook.  There are other features in the plugin the component instance being created (and to be something to teardown). If it's absolutely needed to initiate socket.io connections in the setup() function but still get the teardown feature, a way to do it could be this:

Enable persistence but disable teardown in the setup hook. Wait until the mounted hook to pass in the enabled option to the persisted socket:

```js
setup() {
  ctx.socket = ctx.$nuxtSocket({
    channel: '/index',
    reconnection: false,
    persist: 'mySocket',
    teardown: false
  })
},
mounted() {
  this.$nuxtSocket({
      persist: 'mySocket',
      teardown: true // now the teardown is enabled 
  })
}
```

It's quite late here.

**Comment by udisun** [comment]
> Ok, i've just been using the composition api. Everything works fine if the nuxtSocket is instantiated in the mounted() hook. There are other features in the plugin that depend on the component instance already being created (and to be something to teardown). So it's best put entirely in the mounted() hook when possible. If it's absolutely needed to initiate socket.io connections in the setup() function but still get the teardown feature, a way to do it could be this:
> 
> Enable persistence but disable teardown in the setup hook. Wait until the mounted hook to pass in the enabled option to the persisted socket:
> 
> ```js
> setup() {
>   const ctx = useContext()
>   ctx.$store = ctx.store
>   ctx.socket = ctx.$nuxtSocket({ // works
>     channel: '/index',
>     reconnection: false,
>     persist: 'mySocket',
>     teardown: false // unfortunately, there is no ctx.$on before the component instance is created
>   })
> },
> mounted() {
>   this.$nuxtSocket({
>     persist: 'mySocket',
>     teardown: true // now the teardown is enabled. works because ctx.$on is defined.
>   })
> }
> ```
> 
> But, I still prefer to keep all this setup logic in the mounted() hook.

It worked for you on mounted because you are mixin the composable interface with the options interface.
Your mounted function gets 'this' so it works.
In composition api interface you import 'onMounted' function and call it from inside of the setup function.
Giving it a callback to run on mounted.
Basically everything is written inside the setup function.
I'm already using onMounted inside setup and there you dont have 'this', and using the context object it still cant work with teardown true.
Just a note, I'm using version 1.1.13 as I have to integrate with a server that uses version 2 of socket-io.

**Comment by richardeschloss** [comment]
Your second screenshot is throwing the error because your second code snippet doesn't define socket.value. socket.on would work. However, the main issue seems to be unimplemented ctx.$on and ctx.$emit in the composition api, and I'm currently thinking about how to stub in that missing functionality

**Comment by richardeschloss** [comment]
FWIW, the latest stable version as of 03/30/2021 is 2.6.12.

**Comment by udisun** [comment]
> Your second screenshot is throwing the error because your second code snippet doesn't define socket.value. socket.on would work. Both snippets seems to be over complicating things unnecessarily.
> 
> However, the main issue seems to be unimplemented ctx.$on and ctx.$emit (and potentially other methods) in the composition api, and I'm currently thinking about how to stub in that missing functionality (refs: [removed-apis](https://v3.vuejs.org/guide/migration/introduction.html#removed-apis) and [events-api](https://v3.vuejs.org/guide/migration/events-api.html#overview))

socket.value exists because socket is created using the ref helper.
ref allows you to create 2 way binding.
So the line: 
const socket = ref({})
Creates a wrapper for making socket reactive.
Using its actual value for get/set outside of the html template is done using:
".value" 
But your conclusion is correct and what I was saying from the start.

**Comment by richardeschloss** [comment]
Branch [feat/composition-api](https://github.com/richardeschloss/nuxt-socket-io/tree/feat/composition-api) has just been pushed with some basic fixes:
- implementation for $on, and $emit were created with tiny-emitter/instance (tiny-emitter added as a dependency)
- implementation for $destroy added (requires onUnmounted to be passed in now as an option to nuxtSocket)

Not implemented or changed:
- ctx.$set and ctx.$watch calls 
- namespace config. Some things only partially work right now. 

The working component is [components/Composition1.vue](https://github.com/richardeschloss/nuxt-socket-io/blob/feat/composition-api/components/Composition1.vue)

Be careful trying to make the socket instance itself reactive because of it's circular JSON structure.  

The main file changed was io/plugin.js. Let me know how far these changes get you.

**Comment by richardeschloss** [comment]
1.1.17 released with basic support. [Usage](https://nuxt-socket-io.netlify.app/usage) will have the details, and a fully working example is in [Composition1.vue](https://github.com/richardeschloss/nuxt-socket-io/blob/master/components/Composition1.vue)
