### ISSUE TITLE
How to access to the server before first connection

### ISSUE THREAD

**Issue by laszlo-karpati** [richardeschloss/nuxt-socket-io#188]
Hi!

Is there a way to access to the server (io) instance before the first client connect?

I know, I can access to it from the Svc, like that:
```io.js
export default function(socket, io) {
  //HERE is the io
}
```
but it will not be called until the first client connect, and will be called every time when a new client connects.

Some background:
I would like to use socket.io's auth way, like in the documentation:
```js
// server-side
io.use((socket, next) => {
  const token = socket.handshake.auth.token;
  //validate the token...
});
```

If i put it to the io.js, then it will add a new `.use` at every new connection to the io.

Thanks!

**Comment by richardeschloss** [comment]
Ok, it sounds like there a multiple ways to solve this problem, with some solutions being more available today, but less ideal than others that could come in the future. Here are my thoughts

1. Today's solution could be to use the [`register.ioSvc`](https://nuxt-socket-io.netlify.app/configuration#io-server-overrides) utility provided by `nuxt-socket-io/io/module.js`. This function would accept the socket io instance, and this way you can use work with that instance before registering the IO services. (this would require disabling the automatic server registration with `server: false` and while it can work today with a bit of coding, it's not my favorite)
2. It sounds like a better solution may be a feature request for [registering middlewares](https://socket.io/docs/v3/middlewares/) and I'm thinking an implementation might look like:

`server/io.js`:
```js
export const middlewares = {
  /* Register middleware, sequence matters:
  (socket, next) => {
    const token = socket.handshake.auth.token;
    //validate the token...
  },
  /* remaining middlewares */
}

export default function Svc(io, socket) {
  // io service
}
```

To make the above more versatile, perhaps nuxt-socket-io could also respect an io setter function if it exists:

export function setIO(io) { /* work with io instance */ }

The module could then easily handle this before clients connect:

https://github.com/richardeschloss/nuxt-socket-io/blob/395c52b04e4edf340a8b0169e1cc4aa9d46396bd/io/module.js#L17
```js
  ioSvc(io, ioSvc, nspDir) {
    return new Promise((resolve, reject) => {
      const { default: Svc, middlewares = {}, setIO = () => {} } = require(ioSvc)
     // To-be-added: setIO, register middlewares...
      if (Svc && typeof Svc === 'function') {
```

**Comment by laszlo-karpati** [comment]
Thanks, 
I will try the 1st one.

Thank you for your quick reply!

**Comment by richardeschloss** [comment]
Ok cool. Even if the first one works, we'll keep this issue open because I like the feature request.

**Comment by richardeschloss** [comment]
Middleware registration feature released with 1.1.15. Docs updated with explanations here: https://nuxt-socket-io.netlify.app/configuration#io-middleware-registration

**Comment by laszlo-karpati** [comment]
Thanks @richardeschloss, it woks like the charm in the io.js

io.js:
```js
export const middlewares = {
  backendAuthMiddleware(socket, next) {
    //this will be auth the client at the connection
    console.log('root middleware called!')
    next(new Error('you shall not pass!'))
  },
}

export default function Svc(socket, io) {
   ...
```

but I can't set middleware on a namespace. for example this middleware will not be called:
io/admin.js
```js
export const middlewares = {
  backendAuthMiddleware(socket, next) {
    //this will be auth the client at the connection
    console.log('/admin middleware called!')
    next(new Error('you shall not pass!'))
  },
}

export default function Svc(socket, io) {
   ...
```

I think it would be worth considering to make these middlewares available in the namespaces too, because each namespace has its own middlewares in socket.io.

Thanks!

**Comment by richardeschloss** [comment]
1.1.16 released with this change.

**Comment by laszlo-karpati** [comment]
I've just tried it and it works! 
Awesome, thank you!
