### ISSUE TITLE
Automatic io server registation

### ISSUE THREAD

**Issue by jkljajic15** [richardeschloss/nuxt-socket-io#194]
Hello, thanks for developing this package.

Im having trouble understanding how to implement this in my project. I want to emit an event from my express file when a certain condition is fulfilled. Problem is i have some data that i'm getting from a client. How do i send that req data to io.js file, or am i supposed to import the io.js and use it inside my express api? 

I have red the docs and the issue thats kinda similar to mine here but couldn't figure it out.

`const app = require('express')()

app.post('/', (req, res) => {
  if(req.data == something){
    // how to emit from here?
  }
}
`

**Comment by richardeschloss** [comment]
This has been discussed in greater detail in #166
