### ISSUE TITLE
Where shoud I create the socket

### ISSUE THREAD

**Issue by niwla23** [richardeschloss/nuxt-socket-io#195]
Currently I am creating the socket in index.vue and reference it in the other pages. However, if someone directly goes to another page directly the socket won't be loaded (which makes sense since index.vue was never called).

So what is the best way to do this? I guess I need something like mounted() but not on router level.

**Comment by niwla23** [comment]
index.vue
```js
  mounted() {
    this.socket = this.$nuxtSocket({
      channel: "/",
      persist: "main",
    });
  },
```
join.vue
```js
      this.$store.dispatch("$nuxtSocket/emit", {
        label: "main",
        evt: "join_lobby",
        msg: this.lobbyName,
      });
```

**Comment by niwla23** [comment]
I could do this with plugins that are executed when the site loads. Is that the best pracitce?

**Comment by richardeschloss** [comment]
The other page (join.vue) would use the same `persist` label. The plugin manages it internally. 

join.vue:
```js
 this.socket = this.$nuxtSocket({ // shared with index.vue. 
    channel: "/",
    persist: "main", // means "reuse socket 'main' if it exists"
  });
```

**Comment by niwla23** [comment]
thanks.
