### ISSUE TITLE
Socket.io v4 compatibility

### ISSUE THREAD

**Issue by ricardofiorani** [richardeschloss/nuxt-socket-io#196]
Hello, could you please update the socket.io to the v4 version?

Thank you Richard for this lib.
I wish you have a good day.

**Comment by richardeschloss** [comment]
Eventually when v4 becomes a bit more stable, I'll be happy to upgrade. I've been meaning to update to v4. Thanks for submitting the request so that it gets on the roadmap.

**Comment by richardeschloss** [comment]
Also worth noting: [handling CORS for v4](https://socket.io/docs/v4/server-initialization/#cors). So, this will also have to wire up the socket.io server options to nuxt.config

**Comment by richardeschloss** [comment]
Status update: ok, I was afk for 1 week and am glad to return to see the dependency v4.0.2 appears to be relatively stable. I plan to work on this issue this week, patience requested. Of course, if anyone wants to submit a PR, I think this one could be a good first issue. Fork repo and submit the PR to [issue/196](https://github.com/richardeschloss/nuxt-socket-io/tree/issue/196).

My understanding is the main changes to be made are:
1. How the io instance is initialized
2. How socket.io options are tied from nuxt.config down the io register.
3. Test it (I can help with this if the testing aspect is too daunting)
