### ISSUE TITLE
Vuex not mutating when recieving emits on connection

### ISSUE THREAD

**Issue by gobboo** [richardeschloss/nuxt-socket-io#201]
So whenever a client connects to the socket server, I want to be able to send off an emit to that client to initialize all the previous messages and get player count, then the frontend will put that into a vuex store, however using the config

```ts
      vuex: {
        mutations: [{
          recievedMessage: 'chat/ADD_MESSAGE',
          newClient: 'chat/ADD_CLIENT',
          updateOnlinePlayers: 'chat/UPDATE_PLAYERS'
        }]
      }
```

When they connect, the server sends off 'newClient' however the module never mutates the state, however I am able to do this:

```ts
    this.socket.on('newClient', (client) => {
      chatStore.ADD_CLIENT(client.playerCount, client.messages)
    })
```

Here is the server code
```ts
module.exports = (io) => {
  io.on('connection', (socket) => {
    playerCount++
    
    socket.emit('newClient', { playerCount: playerCount, messages: [] })
    // socket.broadcast.emit('updateOnlinePlayers', playerCount)

    socket.on('disconnect', function() {
      playerCount--;

      socket.broadcast.emit('updateOnlinePlayers', playerCount)
    })

    chat(socket)
  });
}

```
This works, I have the same issue as when trying to broadcast updateOnlinePlayers to all clients and hte frontend doesnt even pick up on it AT ALL, even if I disconnect a client

I might just be dumb but everything else works, when I recieve recievedMessage it mutates the state perfectly fine.

Any clue?

**Comment by richardeschloss** [comment]
Is there any component that still calls `this.$nuxtSocket({})` ? That would still be needed to register the vuexListeners since it's done on a per-socket basis.

**Comment by gobboo** [comment]
Sorry completely missed this comment and the only time I call this.$nuxtSocket is on the index page, going to be moving it to default layout vue page since I want a global socket but thats about it, I dont add a vuex config to that as I've got it in the nuxt config

**Comment by gobboo** [comment]
Also on note with persistance, it doesn't seem to persist my socket connection and it opens a new one

```ts
  io: {
    // module options
    sockets: [{
      url: 'http://localhost:8081'
    }]
  },
  ```
  nuxt.config.js
  
  ```ts
    mounted () {
    const headers: { authorization?: unknown } = {}
    if (this.$auth.loggedIn) {
      const token = this.$auth.$storage.getCookies()['auth._token.cookie'] as string
      headers.authorization = token.replace('Bearer ', '')
    }

    this.socket = this.$nuxtSocket({
      persist: true,
      extraHeaders: headers,
      reconnection: true
    })
  }
  ```
  pages/index.vue
  
  ```ts
    mounted () {
    this.socket = this.$nuxtSocket({
      persist: true
    })
  },
  ```
  components/ChatBox.vue
  
  Seems like it opens a new socket each time and doesnt use the previous opened one?
```
[nuxt-socket-io]: connect main http://localhost:8081 
Object { path: "/socket.io", hostname: "localhost", secure: false, port: "8081" }
nuxt-socket-io.js:969
[nuxt-socket-io]: connect main http://localhost:8081 
Object { extraHeaders: {…}, reconnection: true, path: "/socket.io", hostname: "localhost", secure: false, port: "8081" }
```

Any clue?

**Comment by richardeschloss** [comment]
The `persist` option serves two purposes: First is to persist the socket, the second is to retrieve the persisted socket. So, in order for it to be reused, the ChatBox.vue will also need to have the persist option set to true:

components/ChatBox.vue
```js
mounted() {
  this.socket = this.$nuxtSocket({
    persist: true // really means: re-use the persisted socket that you created in pages/index.vue (or at some higher level). It would only create the socket if it didn't already exist
  })
}
```

The exported types are `{ NuxtSocket, NuxtSocketIoOptions, NuxtSocketIoRuntimeOptions }` and the [Usage docs](https://nuxt-socket-io.netlify.app/usage#type-intellisense) explains how to get the Intellisense working. 

To answer the original question though, my best advice for getting the Vuex mutations working is check the working examples in this git repo, since those are the ones that have been tested against.

**Comment by gobboo** [comment]
It is set to true, and it still creates another Socket, I have 0 clue why.

And I did follow the intellisense guide, however I still recieve the error:

layouts/default.js (moved from index.js page)

import type { NuxtSocket } from 'nuxt-socket-io'

import Vue from 'vue'

import Navbar from '~/components/Navbar.vue'

```ts
export default Vue.extend({
  components: { Navbar },
  data () {
    return {
      socket: null as NuxtSocket | null
    }
  },
  created () {
    const headers: { authorization?: unknown } = {}
    if (this.$auth.loggedIn) {
      const token = this.$auth.$storage.getCookies()['auth._token.cookie'] as string
      headers.authorization = token.replace('Bearer ', '')
    }

    this.socket = this.$nuxtSocket({
      persist: true,
      extraHeaders: headers
    })
  }
})
```

and the ChatBox.vue also has persist enabled as you can see above
