### ISSUE TITLE
Does it support AWS Web socket API Gateway?

### ISSUE THREAD

**Issue by vignesh-uj** [richardeschloss/nuxt-socket-io#202]
I have been trying to use the client to connect to AWS Web socket API but the response status was 101 Switching Protocols, but then it continues reconnecting infinitely with same response.

` this.socket.on("connect", () => {
      console.log('Connected', this.socket.id); // Called, but socket.id will be null
 });

this.socket.on("disconnect", () => {
  console.log('Disconnected', this.socket.id); // Never called
});`

![image](https://user-images.githubusercontent.com/23083306/122040345-4f891e80-cdf5-11eb-9d5a-bb300fc7a051.png)

But the message response from the server is seen in the messages tab:
![image](https://user-images.githubusercontent.com/23083306/122040602-a3940300-cdf5-11eb-8c42-efe902d1cfb9.png)

**Comment by richardeschloss** [comment]
Linked issue: https://github.com/richardeschloss/nuxt-socket-io/issues/156
