### ISSUE TITLE
Emiting message from vuex action takes forever

### ISSUE THREAD

**Issue by mizhgan** [richardeschloss/nuxt-socket-io#206]
Hello!
I'm trying to use Vuex store action to emit some messages by using
```
await this.$store.dispatch(
  "$nuxtSocket/emit",
  {
    label: "messages", 
    evt: "chatMessage",
    msg: msg,
  }
);
```
but this promise never resolves.
I've tried adding callback into chatMessage event on server side like this:
```
socket.on('chatMessage', async (data, callback) => {
  //some code
  callback(true)
}
```
but nothing changed.
What should i do on the server side to aknowledge the client side that the message was received and the promise should be resolved?

**Comment by richardeschloss** [comment]
Was the socket instance persisted prior to dispatching the event? It would have to be persisted under the "messages" label.

Can you please set `localStorage.debug` to 'nuxt-socket-io` to help see the debug log statements?

Here's the code block where the emit takes place to help troubleshoot: https://github.com/richardeschloss/nuxt-socket-io/blob/ca02c8f9c19f4aea43f8cc5fec8b4765dcbf5648/io/plugin.js#L648

Does the server ever receive the client's message?

**Comment by richardeschloss** [comment]
This test passes: https://github.com/richardeschloss/nuxt-socket-io/blob/ca02c8f9c19f4aea43f8cc5fec8b4765dcbf5648/test/specs/Plugin.spec.js#L392
