### ISSUE TITLE
Emit not functioning in even the most basic example

### ISSUE THREAD

**Issue by scalemaildev** [richardeschloss/nuxt-socket-io#208]
After experiencing problems with nuxt-socket-io not triggering some vuex actions in another project of mine (https://github.com/scalemaildev/hashgraph_nuxt_chat), I decided to make a test project to find the root cause. I simply copied the example code from [this tutorial](https://nuxt-socket-io.netlify.app/basic) to a project I have here: https://github.com/scalemaildev/nuxt_socket_test

It should just emit the getMessage function to the heroku app and log the response, but even this basic function isn't working for me. Is there something obviously wrong with the nuxt-socket-io code in that test repo? Or could there be some external factor preventing me from doing any emits? I am not getting any console error messages at all when the function is invoked.

I found a similar issue to mine over here: https://stackoverflow.com/questions/66670998/nuxt-express-sockets-cant-get-connection but that user's solution was to drop nuxt-socket-io entirely and go back to socket-io. I would like to utilize nuxt-socket-io in my project.

Thank you.

**Comment by richardeschloss** [comment]
It's possible the heroku app (my app) went to [sleep](https://blog.heroku.com/app_sleeping_on_heroku) (I haven't used it in awhile and I'm using their free plan). It's working when socket.io client connects to it: https://nuxt-socket-io.herokuapp.com/

![Screenshot from 2021-07-21 22-54-14](https://user-images.githubusercontent.com/5906351/126584155-2bbb036f-e552-407a-9def-297056bda3c8.png) --> emit works. CI / CD system also has all tests pass.

My suggestion is to test on a server instance you have control over. Eventually you'd want your own instance anyway.

nuxt-socket-io gives the user the socket.io-client exactly, so there is no need to choose one or the other...(in that stackoverflow answer, he'd still accomplish the same task if he maintained consistency in the client-side code, which he didn't. He'll also run into other issues if he's mixing basic http requests with socket.io. The two are meant to be separate).

**Comment by scalemaildev** [comment]
Understood, but even using this basic test while running locally does not trigger the vuex action:

nuxt.socket.io
```
modules: [
    'nuxt-socket-io'
  ],

  io: {
    sockets: [{
      name: 'home',
      default: true,
      url: 'http://localhost:3000',      
      vuex: {
	actions: ["TEST_FUNCTION"]
      }
    }]
  },
```

/store/index.js
```
export const state = () => ({});

export const actions = {
  TEST_FUNCTION () {
    console.log('emit worked');
  }
};
```

/pages/index.vue
```
mounted () {
    this.socket = this.$nuxtSocket({
      name: 'home'
    })
  },
  methods: {    
    doStuff() {
      console.log('method triggered')
      this.socket.emit('TEST_FUNCTION', (resp) => {
	console.log(resp)
      })
    }
  }
```

I can even see the action in the console output of the socket:
![Screenshot_20210723_145653](https://user-images.githubusercontent.com/15042849/126835007-124ca364-9157-49fe-8e05-c40b99064d14.png)

Is there something basic I'm misunderstanding about nuxt-socket-io? I've been following [this tutorial](https://javascript.plainenglish.io/introduction-to-nuxt-socket-io-b78c5322d389) and according to that I should be able to trigger the TEST_FUNCTION by emitting 'TEST_FUNCTION' to my one and only socket.

**Comment by richardeschloss** [comment]
It will work if the *server* emits the TEST_FUNCTION event.

**Comment by scalemaildev** [comment]
Thanks managed to figure it out https://github.com/scalemaildev/hashgraph_nuxt_chat
