### ISSUE TITLE
NuxtSocketOpts with Typescript

### ISSUE THREAD

**Issue by matthiasbaldi** [richardeschloss/nuxt-socket-io#210]
Could it be, that the `NuxtSocketOpts` interface is not completely defined?
I found in my opinion the following to points which may could improved in further versions.

- It would help when the NuxtSocketOpts interface is exported, so the developer can define a variable with that type and the corresponding socket configuration
- In may case, may a failure in the workspace configuration, I was not able to get the extended `SocketIOClient.ConnectOpts` properties. When I open your types.d.ts I got the error `Namespace '"node_modules/socket.io-client/build/index"' has no exported member 'ConnectOpts'.`.
May there changed something in the underlying Socket.io client implementation. I found in the [manager.d.ts file](https://github.com/socketio/socket.io-client/blob/master/lib/manager.ts#L208) the `ManagerOptions` with similiar properties. May you have to change the extends in your source?

Thank you.

**Comment by richardeschloss** [comment]
Hi, thanks for bringing this to my attention. The types.d.ts file was written before the latest socket.io-client, and it's possible that new client has changed the names of its types.

It's possible that this line needs to change:
https://github.com/richardeschloss/nuxt-socket-io/blob/ca02c8f9c19f4aea43f8cc5fec8b4765dcbf5648/io/types.d.ts#L129

To extend the new `ManagerOptions` instead. If you are able to tweak the types file as it sits in your node_modules/nuxt-socket-io/types.d.ts, please let me know if your issue can be resolved. It seems like your really close to the solution already.

**Comment by matthiasbaldi** [comment]
If I add the following import
```typescript
import { ManagerOptions } from 'socket.io-client/build/manager';
```

and change the extends of this line https://github.com/richardeschloss/nuxt-socket-io/blob/ca02c8f9c19f4aea43f8cc5fec8b4765dcbf5648/io/types.d.ts#L129 to the following definition:

```typescript
export interface NuxtSocketOpts extends Partial<ManagerOptions> {
```
Then it will work as expected. I think the `@types` dependency is not longer required because they (socket.io-client) already included types in their dist folder. May also check that.

**Comment by richardeschloss** [comment]
Ok cool. Do you want to fork and submit a PR? That way you get contribution credit.

If so, please submit PR to https://github.com/richardeschloss/nuxt-socket-io/tree/issue/210 (branch/210 --> branch/210)

**Comment by matthiasbaldi** [comment]
Ya, I could do that.

**Comment by matthiasbaldi** [comment]
@richardeschloss Did you ment a PR to the issue/210 branch in your repository?
Sorry I did not get that 😏😅

**Comment by richardeschloss** [comment]
Either to issue/210 or to development. I think it's cleaner to go to issue/210 to make comparisons easier
