### ISSUE TITLE
How to use window.location in SSR 

### ISSUE THREAD

**Issue by matthiasbaldi** [richardeschloss/nuxt-socket-io#222]
How would you @richardeschloss use your lib in the SSR mode in nuxt?
In my application I have a Dockerfile and I want to set the url dynamically, based on the window.location.
Everytime I get a `window is not defined` error, which means that the configuration is getting executed in the SSR mode.

But when I don't set the socket client configuration in the `nuxt.config.js` to use your window.location fallback (#93) it will fail because no socket configuration was defined.

```javascript
// nuxt.config.js
    io: {
        sockets: [
            {
                name: 'default',
                default: true,
                ...(isProd
                    ? window.location
                    : { url: 'http://localhost:4000' }),
            },
        ],
    },
```

```javascript
// index.vue
// ...
const socket = this.$nuxtSocket({
            name: 'sslcache',
            statusProp: 'socketStatus',
            ...(isProd
                    ? window.location
                    : { url: 'http://localhost:4000' }),
            path: '/api/ws',
// ...
```

Do you have any idea how I could solve this issue?
Because I have to set the url depending on a set environment in the container.

Thank you for your support.

**Comment by richardeschloss** [comment]
Normally, the server does not have a browser environment, and thus `window` will always be undefined there. You could try to use something like `browser-env` and/or jsdom-global, which would define a window-object, although I mainly reserve that for testing use. 

My opinion is that it's easier to set the code that depends on client-only features as client only.

**Comment by richardeschloss** [comment]
The easiest solution is to omit the url entirely, and let socket.io-client handle it. It will default to the client's window.location
https://socket.io/docs/v3/client-api/index.html#io-url-options
