### ISSUE TITLE
Automatic IO Server Registration not register server/io.ts and use ioSvc setting wrong result

### ISSUE THREAD

**Issue by ohashi14715369** [richardeschloss/nuxt-socket-io#224]
`~/server/io/*` namespaces automatic registration any ext(js|ts|mjs).
https://github.com/richardeschloss/nuxt-socket-io/blob/dbb73a48d6c52cdaf43f90c182b0f49cc0d46b24/io/module.js#L47

But `server/io.ts` not automatic registation because decided `.js` ext only.
https://github.com/richardeschloss/nuxt-socket-io/blob/dbb73a48d6c52cdaf43f90c182b0f49cc0d46b24/io/module.js#L99

I instead use this config,
```
// nuxt.config.ts
  io: {
    server: {
      ioSvc: '~/server/io.ts'
    }
  }
```
this code result `nspDirFull` value is `<project_dir>/.ts`... namespace auto registration not working.
https://github.com/richardeschloss/nuxt-socket-io/blob/dbb73a48d6c52cdaf43f90c182b0f49cc0d46b24/io/module.js#L87-L103

**Comment by richardeschloss** [comment]
Hi, thanks for bringing this to my attention. I'll have a look at your PR.

**Comment by richardeschloss** [comment]
1.1.23 released with the fix.
