### ISSUE TITLE
Chrome warning about sub resources

### ISSUE THREAD

**Issue by scalemaildev** [richardeschloss/nuxt-socket-io#232]
When using nuxt-socket-io in a production environment (NGINX hosting within a Docker container on AWS Elastic Beanstalk) I'm seeing a strange warning in the chrome console about accessing subresources:

![Screenshot_20210929_185119](https://user-images.githubusercontent.com/15042849/135363907-da2b1275-520a-48ba-8cb1-8f56248e8fac.png)

After looking around I found that it's related to the socket.io module and [they posted a solution here.](https://github.com/socketio/socket.io/issues/3929) Is there any way to implement this solution with nuxt-socket-io?

Also, a possibly related issue: I had to turn off the Brave browser shields (a sort of adblocker) in order for the socket to function. Otherwise I got an ERR_BLOCKED_BY_CLIENT error. This typically only happens for ads and banners. It did not need to be turned off in development, only when hosted in production. Do you think this might be related to the above issue?

EDIT: I think it would also be useful if I include a snippet from my app in case this was just human error on my part in configuring things.

nuxt.config.js io entry
```
io: {
        server: {
            cors: {
                origin: "*"
            }
        },
        sockets: [{     
            default: true,
            name: 'mainSocket',
            url: 'http://localhost:3000',
            vuex: {
                actions: [{ newHCSMessage: 'sessionStorage/PROCESS_MESSAGE' }]
            }
        }],
    },
```

**Comment by scalemaildev** [comment]
Update on this. I tried going this route with the socket.io issue solution, but still no luck:

nuxt.config.js
```
io: {
        server: {
            cors: {
                origin: "*"
            },
            extraHeaders: {
                "Access-Control-Request-Private-Network": true
            }
        },
        sockets: [{     
            default: true,
            name: 'mainSocket',
            url: 'http://localhost:3000',
            vuex: {
                actions: [{ newHCSMessage: 'sessionStorage/PROCESS_MESSAGE' }]
            }
        }],
    },
```

server/io.js
```
export default function(socket, io) {
    io.engine.on("headers", (headers) => {
        headers["Access-Control-Allow-Private-Network"] = true;
    });
    
    return Object.freeze({

   ...
```

**Comment by richardeschloss** [comment]
Can we please wait until https://github.com/socketio/socket.io/issues/3929 is closed?

**Comment by scalemaildev** [comment]
This was actually a misconfigured socket on my part.

I had left the url in nuxt.config.js as 'localhost' so the app was still trying to connect to my local machine when it was hosted on AWS EBS. Since I still had the docker container up and running on the same port, it actually found my container and served it to me. Hence the console warning.

Since I removed the line specifying the url, the socket defaulted to 'window.location' and is working perfectly.
