### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by PitPietro** [richardeschloss/nuxt-socket-io#233]
The Demo website hosted on Heroku: [nuxt-socket-io.herokuapp.com/](https://nuxt-socket-io.herokuapp.com/) is not working.

![screen_shot](https://user-images.githubusercontent.com/60300699/135409760-9e2f82e1-b588-4c72-a749-f4087e6ea39e.png)

**Comment by richardeschloss** [comment]
Refresh. it's the new month again. It's working.
