### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by MoonCheung** [richardeschloss/nuxt-socket-io#238]
How to solve these problems? Expect to install these dependency libraries to work, please help me? 
![image](https://user-images.githubusercontent.com/19801190/137576470-b65189fb-cc76-46a7-bf4b-e472918b03fa.png)
The project relies on the following libraries:
nuxt：^2.15.2
nuxt-socket-io：^1.1.24

**Comment by richardeschloss** [comment]
Hi, what code are you using to encounter this error? My guess is that there are some commonJS files that just need to be converted to ESM. I.e., if there are files with `module.exports = ...`, those just need to be replaced with `export default`. 

In this repo, there are a few .ts files used just for the automated testing purposes, which need `module.exports`, but those don't get published with the module to npm.

**Comment by richardeschloss** [comment]
What version of nodejs are you using? It's possible your nuxt.config may need to be ESM? (This was tested against node LTS; i.e., v14.17.5)
