### ISSUE TITLE
Please Update plugin.js to fix "Cannot read property 'length of undefined"

### ISSUE THREAD

**Issue by Timothy-Y-H-Lee** [richardeschloss/nuxt-socket-io#24]
Please Update plugin.js

Hello?
First of all thank you for your module sharing.

If I change the mutations as below at nuxt.config.js, my Chrome web browser said: "Cannot read property 'length of undefined".
Could please test the source?

- nuxt.config.js
        vuex: {
          // mutations: [{ progress: 'examples/SET_PROGRESS' }],
          actions: [{ chatMessage: 'FORMAT_MESSAGE' }],
          emitBacks: ['examples/sample', { 'examples/sample2': 'sample2' }]
        }

- plugin.js
before:      // if (groupOpts.length && groupOpts.length > 0) {
to be:      if (groupOpts && groupOpts.length > 0) {

**Comment by richardeschloss** [comment]
Hi Timothy,

Thank you for helping with this! I appreciate it! I'll try to get a fix in today.

I think in that condition, I'll specifically check to see that it's defined and an array. 

Rich

**Comment by richardeschloss** [comment]
PR #25 merged into development. A new release should be coming soon.

**Comment by richardeschloss** [comment]
v1.0.5 pushed to npm.

**Comment by Timothy-Y-H-Lee** [comment]
Great! Thanks for update the nuxt-socket-io :)
