### ISSUE TITLE
Nuxt3 prep

### ISSUE THREAD

**Issue by richardeschloss** [richardeschloss/nuxt-socket-io#241]
Nuxt3 / Vue3 will require considerable code refactoring.

**Comment by richardeschloss** [comment]
nuxt-socket-io v2.x pushed now. More details in the changelog. Main changes:

- Changed package entirely to ESM
- ERB-templates (<%options />) being phased out in favor of runtime config. This greatly simplified the plugin and it's tests.
- Simplified the namespace config to just the string-formatted entries. 
- Added promisifed socket.emitP and socket.onceP methods. Docs to be updated eventually.
- Cleaned up the demo site a bit.

Nuxt3 is still in beta and the plan will be to release v3.x of this module to be Nuxt3 compatible.

**Comment by richardeschloss** [comment]
Ok, I just saw the emojis...I'll try to get this nuxt3 compatible asap... i

**Comment by richardeschloss** [comment]
[feat/nuxt3](https://github.com/richardeschloss/nuxt-socket-io/tree/feat/nuxt3) pushed. It sorta / kinda works with quirks. 

The quirks are: 
- [ ] Nuxt3 currently is not responding to the "listen" hook, so the nuxt-socket-io module will rely on using http://localhost:3001 (port 3000 + 1) for it's default socket.IO server. 
  - [ ] This also means that the CORS option passed to socket.io has to allow connections from the nuxt app (in this case, http://localhost:3000). This is manually specified because Nuxt3 warns that it's server properties will be deprecated. If they hold onto that then the manual entry can be avoided.
- [ ] Nuxt team is think about the best way to make global storage more versatile; i.e., so you're not limited to just Vuex, but will also have options to use other stores. One of the quirky results of the redesign is it appears only namespaced Vuex stores are being registered, and anything at the root store is not. This occurs when the plugin is added (see https://github.com/nuxt/framework/issues/2407). It seems like store/index.js, store/root.js are ignored, and if the filename has "index" in it, the "index" gets removed. 
  - [ ] It's possible that nuxt-socket-io plugin can be smarter with the Vuex options and maybe even cleaner. I.e., maybe all IO channels automatically get their own namespaces in Vuex. That'd be clean and spiffy, perhaps?). The idea would be to scaffold the boring boilerplate and still keep things organized. 
  - [ ] But note: it seems that for some reason, simply having `defineNuxtPlugin` causes the root store to disappear. Maybe this is for security reasons? Maybe root store is non-ideal and non-clean design? 
- Other than that, things seem to be working fine. If you're daring to take it for a spin... good luck! It's only been manually tested to a reasonable degree. You can install it with: 
- 
> npm i github:richardeschloss/nuxt-socket-io

**Comment by richardeschloss** [comment]
feat/nuxt-edge pushed and tested. It can now be used with Nuxt-edge :rocket: 

To install, this command should let you install from the branch in github:

> npm i "git+https://github.com/richardeschloss/nuxt-socket-io.git#feat/nuxt-edge"

**Comment by richardeschloss** [comment]
A weird issue is occurring, only in the deployed version. It works fine in this repo, but not when it's in node_modules.

```
The requested module '/node_modules/parseuri/index.js?v=af9f18fe' does not provide an export named 'default'
```

I'm not sure why this is happening.

**Comment by richardeschloss** [comment]
Here's the workaround for the previous issue. Several dependencies out there are still in commonJS format and vite doesn't like that. The following config had to be provided to Vite to get things to work:

```js
  bridge: {
    vite: true
  },
  vite: {
    optimizeDeps: { // This was the workaround
      include: ['parseuri', '@socket.io/component-emitter', 'parseqs', 'yeast', 'engine.io-client',
        'backo2', 'debug', 'tiny-emitter/instance.js']
    },
}
```

**Comment by PMLS3** [comment]
Hi @richardeschloss , is the workaround for nuxt-bridge or nuxt3?

**Comment by richardeschloss** [comment]
The workaround is currently for nuxt-bridge.

**Comment by richardeschloss** [comment]
Ok, I'm able to get this workaround to work with nuxt3:
```js
import { defineNuxtConfig } from 'nuxt3'
export default defineNuxtConfig({
  vite: {
    optimizeDeps: { // This was the workaround
      include: [
        'parseuri', // <-- updated this
        '@socket.io/component-emitter', 
        'parseqs', 
        'yeast', 
        'engine.io-client',
        'backo2', 
        'debug', 
        'tiny-emitter/instance.js'
      ]
    }
  },
...
}

**Comment by richardeschloss** [comment]
Nuxt3 support pushed :rocket: :rocket: :rocket:  (working workaround shown in previous comment. https://github.com/nuxt/framework/pull/2521 was just merged a few days ago)
(but please understand, only *basic features* work. The features that relied on Vuex are temporarily disabled because of the ongoing discussion for global state management. For the time being, it may turn out that `useState` will get you what you want and maybe that will be the route nuxt-socket-io's plugin goes (although pinia looks promising with its type support).

See table above for installation instructions: https://github.com/richardeschloss/nuxt-socket-io/issues/241#issuecomment-999266321

**Comment by richardeschloss** [comment]
Status update: restored most features. One key change was instead of relying on registering a vuex module, I now just use `useState` and manage that in `nuxtSocket`. 

The only missing / disabled feature is the Vuex options (i.e., the feature that handles message streaming into Vuex). But honestly, `useState` seems to be insanely easier to use and I think people will have much more flexibility with that.

**Comment by richardeschloss** [comment]
Status update: ALL features restored (feat/nuxt3 branch has the latest changes), with one key difference: vuex options became "iox" options. It's still a very similar concept, but it's actually easier now! (Folks will just have to unlearn Vuex a little bit to understand `useState`, but I think it's the easier way to go!)

So now, instead of use passing in "vuex" options, like "mutations", "actions", simplify life completely with just the arrow syntax:

```js
iox: [
  /* IO Event  to / from State variable */
  'chatMessage --> chats/message', // When chatMessage event received, send to ioState chats.message
  'progress --> examples/progress', // When progress event received, send to ioState examples.progress
  'examples/sample <-- examples/sample', // When examples.sample changes in ioState, send back the event "examples/sample"
  'examples/someObj', // Bidirectional
  'bidirectional' // Bidirectional
],
```

Then, accessing the ioState is *super easy*. I give two alternatives:

1. [Easiest] "$ioState" gets provided by the plugin, so you can easily use `this.$ioState().value` to get the state. For example, to get "chats/message" above, it would be `this.$ioState().value.chats.message` (most likely, you'd use "?" to wait for all parts to be truthy: `this.ioState().value?.chats?.message`)

2. [Easy too] you can also `import { ioState } from 'nuxt-socket-io/lib/plugin.js' and use it in the same manner

**Comment by richardeschloss** [comment]
Released to npm with tag "next":
> npm i nuxt-socket-io@next

**Comment by richardeschloss** [comment]
Update 01/27/2022: pushed extended type support for Nuxt3. To take full advantage of this, it appears I need to have a types definition file in project root:

[appRoot]/types.d.ts
```js
import 'nuxt-socket-io/lib/types' 
```

I'm not as familiar with tsconfig.json, does anyone know the config setting that would accomplish the same thing?
