### ISSUE TITLE
Invalid type imports

### ISSUE THREAD

**Issue by MayurPrajapati** [richardeschloss/nuxt-socket-io#245]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `nuxt-socket-io@1.1.24` for the project I'm working on.

Seems like there are some breaking changes in socket-io lib that make this fail.
It was type import issues that were referring to old socket-io-client types.
I tried the below solution & it worked.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/nuxt-socket-io/io/types.d.ts b/node_modules/nuxt-socket-io/io/types.d.ts
index f2a6a83..c54d12e 100644
--- a/node_modules/nuxt-socket-io/io/types.d.ts
+++ b/node_modules/nuxt-socket-io/io/types.d.ts
@@ -1,7 +1,5 @@
 import { Module } from '@nuxt/types';
 import * as SocketIOClient from 'socket.io-client';
-import { ManagerOptions } from 'socket.io-client/build/manager';
-import { Socket } from 'socket.io-client/build/socket';
 import Vue from 'vue';
 
 /**
@@ -128,7 +126,7 @@ interface NuxtSocketIoServerOpts {
   port?: number;
 }
 
-export interface NuxtSocketOpts extends Partial<ManagerOptions> {
+export interface NuxtSocketOpts extends Partial<SocketIOClient.ManagerOptions> {
   /** Name of the socket. If omitted, the default socket will be used. */
   name?: string;
   /**
@@ -278,7 +276,7 @@ interface NuxtSocketIoRuntimeOptions {
   info?: boolean;
 }
 
-interface NuxtSocket extends Socket {};
+interface NuxtSocket extends SocketIOClient.Socket {}
 
 type Factory = (ioOpts: NuxtSocketOpts) => NuxtSocket;
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by richardeschloss** [comment]
Can you please upgrade to 2.x and re-test?

**Comment by richardeschloss** [comment]
Hi I confirmed this issue. Thanks for providing the feedback and will plan to rollout the fix in the next release.
