### ISSUE TITLE
Auth option for IO configuration

### ISSUE THREAD

**Issue by MegaCrafter** [richardeschloss/nuxt-socket-io#246]
Socket.io client has an option to provide an auth object on io connection. Such as:
```ts
io({
  auth: {
    token: 'abc'
  }
});
```

This token can then be used as `socket.handshake.auth.token` on the server side. Can you add this option to the io configuration?

**Comment by richardeschloss** [comment]
Yes, that can be passed in nuxt.config:

```js
io: {
  server: { 
    auth: { ... }
  }
}
```

It's implemented here:
https://github.com/richardeschloss/nuxt-socket-io/blob/b09cbf0e1580a5e13d4b400ed6ba457aa1de174f/lib/module.js#L119
