### ISSUE TITLE
question: port 3000 for automatic server creation

### ISSUE THREAD

**Issue by dargmuesli** [richardeschloss/nuxt-socket-io#248]
Hey there, thank you for the great plugin!
Trying to set it up I'm wondering: the automatic server creation seems to [default to port 3000](https://github.com/richardeschloss/nuxt-socket-io/blob/41ca100f5702936422bab784beaffd0ecfa2397a/lib/types.d.ts#L120). My confusion lies in that the Nuxt web server itself starts on port 3000 already and, as far as I know, two applications cannot listen on the same port.
My workaround now would be to change the server port configuration to port 3001 or similar, but do I miss something making the default of port 3000 work too?

**Comment by richardeschloss** [comment]
Hi, the [server overrides](https://nuxt-socket-io.netlify.app/configuration/#io-server-overrides) would be used if you want the IO server to listen on a different port. 

```js
io: {
  server: { port: 3001 } // listen on a port different from the one Nuxt uses.
}
```

The Nuxt and IO server can share the port, with socket.io using it's own protocol for the connections made to it.
