### ISSUE TITLE
Question: Connect to LaravelEcho & how to manage auth on this plugin with refresh-token

### ISSUE THREAD

**Issue by devzom** [richardeschloss/nuxt-socket-io#249]
Hey there,

I'm creating this question due to missing information in documentation.

1.  Is this plugin able to work with  laravelEcho?
2. How to manage changing token when it get's refresh?

Thank You in advance for any response.

**Comment by richardeschloss** [comment]
I'm not sure, I think LaravelEcho requires wrappers around it's own libraries? It seems like it's a different implementation of websockets than socket.io.
