### ISSUE TITLE
Headers not being sent

### ISSUE THREAD

**Issue by kamil-hammouche** [richardeschloss/nuxt-socket-io#250]
Hello,

I've read both these issues :
- https://github.com/richardeschloss/nuxt-socket-io/issues/207
- https://github.com/richardeschloss/nuxt-socket-io/issues/96

I have tried both methods but I am still unable to send extra headers to my server.

nuxt.config.js file :
```
io: {
    sockets: [{
      url: process.env.WEBSOCKETS_URL ?? 'ws://localhost:4500',
    }],
  },
```

My component (first-try) :
```
this.socket = this.$nuxtSocket({
      default: true,
      extraHeaders: {
        Authorization: "abcd",
      },
    });
```

My component (second-try) :
```
this.socket = this.$nuxtSocket({
      default: true,
      transportOptions: {
        polling: {
          extraHeaders: {
            Authorization: "abcd",
          },
        },
      },
    });
```

I'm using the version 2.0.0 but I tried the 1.1.24 aswell and none worked.

Is there something I am missing ?

Best regards,

**Comment by richardeschloss** [comment]
From looking at the [transport options](https://socket.io/docs/v4/client-options/#transports), it appears that socket.io-client is expecting an array of strings for transports. So I'm guessing the code has to be refactored like this:

```js
this.socket = this.$nuxtSocket({
  default: true,
  transportOptions: ['polling'],
  extraHeaders: {
    Authorization: "abcd",
  }
});
```

Per [extraHeaders](https://socket.io/docs/v4/client-options/#extraheaders), it appears you are on the right track in using polling transport. Setting `localStorage.debug` to "socket.io:client*" should reveal what socket.io-client is doing. nuxt-socket-io is passing the provided options to it.

**Comment by kamil-hammouche** [comment]
Well, thank you very much for your quick response!
With the transport options as an array, it worked.
Moreover, I noticed something else on my back-end. The Authorization key, no matter how I write it, is sent as lowercase. It means that on my front, I send the header as `Authorization` but it is received as `authorization` on my back-end. 
This is a precious information to know for other that might create an issue regarding that 🙂
