### ISSUE TITLE
'persist' has wrong type definition

### ISSUE THREAD

**Issue by alex-lechner** [richardeschloss/nuxt-socket-io#254]
Hello, thank you for this great library!

According to the documentation, the Nuxt socket option `persist` can take a `string` as a value in order to reference it in other components. However, I get an error from typescript that only a `boolean | undefined` is allowed. Everything works fine and I can reference the nuxt socket by the `label` but it's a "cosmetic" linting error.

<img width="544" alt="Screen Shot 2022-01-21 at 14 32 43" src="https://user-images.githubusercontent.com/26361781/150528604-bfe4b28b-b79f-414e-bb01-5767876eead5.png">

**Comment by richardeschloss** [comment]
Hi sorry for the inconvenience. 2.0.3 should contain the fix now.
