### ISSUE TITLE
MVP Nuxt3 + Socket.Io

### ISSUE THREAD

**Issue by fabianwohlfart** [richardeschloss/nuxt-socket-io#256]
Hey,

So in the meanwhile between nuxt2 and support for nuxt3...
Do you guys have a minimum setup of socket.io + nuxt3?
Like nothing fancy, just getting socket up and running under it's own path?
So I can adjust everything else on my own behalf?

I cannot wrap my head around on how to register it as a standalone server middleware with h3...
Or am I completly mistaken?

server/socket.js
```javascript
import { createApp } from 'h3'
import { createServer } from 'http'
import { Server } from 'socket.io'

const app = createApp()
app.use('/', () => 'Hello IO!')

const httpServer = createServer(app)
const io = new Server(httpServer)
export default ???
```

nuxt.config.js
```javascript
serverMiddleware: [
   { path: '/io', handler: '~/server/socket.js' }
]
```

**Comment by peteromano** [comment]
Unless the docs aren't nuxt3 compatible yet (seems like it is), the docs seem pretty good: https://nuxt-socket-io.netlify.app/configuration#io-server-overrides

**Comment by fabianwohlfart** [comment]
Sorry did not see that there is @next branch yet...

**Comment by richardeschloss** [comment]
Hi, nuxt3 branch works (I use it everyday), but updating the docs are still be postponed until nuxt3 is officially released and determined to be stable. The most up-to-date information about the nuxt3 support for the time being is in this issue: https://github.com/richardeschloss/nuxt-socket-io/issues/241
