### ISSUE TITLE
Property 'emitP' does not exist on type 'NuxtSocket'.

### ISSUE THREAD

**Issue by Sebastian-tengai** [richardeschloss/nuxt-socket-io#264]
emitP seems to be missing in the types.d.ts

![image](https://user-images.githubusercontent.com/80793061/159356981-b63a132d-5a52-4bdb-aecc-d377a4efe3a8.png)

**Comment by richardeschloss** [comment]
Hi thanks for bringing that to my attention. I've been meaning to update the types and was waiting to see if anyone was going to use that extended method. I'll try to get to updating the types soon.

**Comment by richardeschloss** [comment]
Ok, I just updated the types and pushed the changes to npm. 
https://github.com/richardeschloss/nuxt-socket-io/blob/5c04b4215584d2af1a4bdf1b02e5c987a68e703a/lib/types.d.ts#L279
