### ISSUE TITLE
Please configure sockets

### ISSUE THREAD

**Issue by azmifitra** [richardeschloss/nuxt-socket-io#265]
Why am i getting this error? it works fine on localhost, but in production it won't work. 
![image](https://user-images.githubusercontent.com/88577544/164389001-57ed7483-2983-49a1-977f-a2510a5b6a2c.png)

this is my nuxt.config.js
![image](https://user-images.githubusercontent.com/88577544/164389131-8aca74a5-5ede-40e8-9bda-e16a60dac2ed.png)

and this on my mounted component (calling nuxt-socket-io with headers)
![image](https://user-images.githubusercontent.com/88577544/164389295-b6a60618-0743-4818-9e83-13177f7385d7.png)

am i doing it wrong? because it works fine on my localhost, i can receive a realtime message and send message

**Comment by richardeschloss** [comment]
I'm not exactly sure why it's working in one environment but not in another, but to help troubleshoot, this is the line that may help:
https://github.com/richardeschloss/nuxt-socket-io/blob/589d552e62e46d4449adab43c570a9479c8d430f/lib/plugin.js#L925

It's pulling sockets from merged options (from nuxt config options `io` and from the runtime config $config.io). 

The validation is performed here:
https://github.com/richardeschloss/nuxt-socket-io/blob/589d552e62e46d4449adab43c570a9479c8d430f/lib/plugin.js#L932

If `sockets` is not an Array or if it's an array with length 0, it'll throw the error.

**Comment by azmifitra** [comment]
But my sockets is array and have length (1), that's why on localhost i didn't receive the error. I still don't understand why on production the nuxt.config won't read the sockets array.

**Comment by richardeschloss** [comment]
What happens when you put a breakpoint on the line I showed? What are the `mergedOpts` in production? 

I'm guessing production might need the config also specified in the runtime config. (although this wasn't needed for me when I built for production at Netlify).

https://github.com/richardeschloss/nuxt-socket-io/blob/589d552e62e46d4449adab43c570a9479c8d430f/nuxt.config.js#L8

**Comment by azmifitra** [comment]
When I console.log(this.$config) on my mounted lifecycle, the result on my localhost like this (I guess these are mergedOpts that you are talking about) 
![image](https://user-images.githubusercontent.com/88577544/164958128-d7f28d1f-a975-4698-bb9e-4f7c3b91a143.png)

But on the production, io and nuxtSocketIo are not there, its just my axios that showed up. I already put my io in my both public and private runtime config since the first time 
![image](https://user-images.githubusercontent.com/88577544/164958285-6d53b8f6-3c75-4826-b038-8c0b69d65154.png)

**Comment by richardeschloss** [comment]
Ok, one thing I notice is your vuex options has to go in to the sockets entry (since vuex is configured per socket).

So, your config needs to be:

```js
io: {
  sockets: [{
    name: ...
    url: ...
    vuex: { ... }
  }]
}
```

While this may not solve your issue, it's still a change that would need to be done to use the vuex feature. But, to address the problem at hand, that requires debugging your build step and runtime in production (and paying attention to any warnings the build step gives you).

**Comment by louislspn** [comment]
Hello, did you find a fix for this error ? I have the exact same problem as @azmifitra described.

**Comment by richardeschloss** [comment]
@louislspn , can you please share your config, just the socket.io related config?

**Comment by louislspn** [comment]
@richardeschloss Here is my io config :

```
io {
  sockets: [
    {
      name: 'default',
      url: process.env.SOCKET_SERVER_URL,
      default: true,
      transports: ['websocket'],
      upgrade: false,
      vuex: {
        mutations: [
          'instance:updated --> instance/update'
        ],
        actions: [
          'instance:created --> instance/redirect'
        ]
      }
    }
  ]
}
  ```
  
 It works well in nuxt static mode with `npm run generate` but not in server-mode.

**Comment by richardeschloss** [comment]
Ok, your "io" needs a ":" between it and the next "{".

**Comment by louislspn** [comment]
Sorry, wrong copy/paste. The `:` aren't missing in my config.

**Comment by richardeschloss** [comment]
Ok, I'm not sure why your seeing the error, but to help troubleshoot, the line of interest may be:
https://github.com/richardeschloss/nuxt-socket-io/blob/589d552e62e46d4449adab43c570a9479c8d430f/lib/plugin.js#L925

When `sockets` is extracted from `mergedOpts`, it's supposed to be an Array of length > 0. If it fails that condition, that's what causes the error. Your config looks fine, but without actually debugging your code, I'm not sure why the error is occurring.

**Comment by richardeschloss** [comment]
What does your code look like in the component?

**Comment by louislspn** [comment]
```
<template>
  <div id="app">
    <Nuxt />
  </div>
</template>

<script>
export default {
  beforeMount () {
    this.$root.$socket = this.$nuxtSocket({ name: 'default' })
  }
}
</script>
```

Here is my code in my layout.
It works as expected in local and in production (static mode) but I have the mentioned error in production with ssr enabled.

I will have a look at `mergedOpts`, thank you !

**Comment by richardeschloss** [comment]
Ok, I'm not entirely sure why there's an issue in ssr. Does that code work if it's moved to a `mounted` hook? Does it have to be in `beforeMount`?
