### ISSUE TITLE
Doesn't seem to work with Nuxt 3 RC

### ISSUE THREAD

**Issue by Redemption198** [richardeschloss/nuxt-socket-io#267]
I've installed the @next version on a small Nuxt 3 RC3 app with the settings from the setup section in the readme, but it doesn't seem to work.

When Nuxt starts it warns me about `parseuri` not being found (`ERROR  Failed to resolve force included dependency: parseuri`), I've already tried the [Vite workaround](https://github.com/richardeschloss/nuxt-socket-io/issues/241#issuecomment-1006180815) without any success.

By doing some tests I noted that this module is accessing to `publicRuntimeConfig` which has been replaced by `runtimeConfig`, it is documented [here](https://github.com/nuxt/framework/discussions/2883), so it is probably breaking the module.

**Comment by richardeschloss** [comment]
Does your code work with nuxt3 version 3.0.0-27376999.6abf75d ? That is the version this module's [working nuxt3 branch](https://github.com/richardeschloss/nuxt-socket-io/blob/feat/nuxt3) uses. 

I appreciate the suggestion and I can look into the changes to naming conventions

**Comment by richardeschloss** [comment]
Tested and deployed with tag nuxt3rc .

> npm i nuxt-socket-io@nuxt3rc
