### ISSUE TITLE
How to listen on reconnect events

### ISSUE THREAD

**Issue by WhatzzUpp** [richardeschloss/nuxt-socket-io#269]
plugin Version: "nuxt-socket-io": "^2.0.3",

Hey folks!

I need a clue how to implement to listen on a reconnect event.
Have tried the following events:

```javaScript
 this.socket = this.$nuxtSocket({
      transports: ['websocket'],
      reconnection: true,
      channel: '/',
      emitTimeout: 1000, // 1000 ms
      reconnectionDelay: 1000,
      reconnectionAttempts: 60,
      teardown: false,
    })

    this.socket.on('reconnect_attempt', (msg, cb) => {
      /* Handle event */
      console.log('reconnect_attempt :>> ', msg)
    })
    this.socket.on('reconnect', (msg, cb) => {
      /* Handle event */
      console.log('reconnect :>> ', msg)
    })
    this.socket.on('reconnecting', (msg, cb) => {
      /* Handle event */
      console.log('reconnecting :>> ', msg)
    })
```
Neither reconnect_attempot nor reconnecting or reconnect are fired during the reconnecting process and after successfully.
Other events like disconnect or connect works. 

Any idea what im doing wrong?

Thanks for your time and helpt!

**Comment by richardeschloss** [comment]
What version of socket.io / nuxt-socket-io is installed? The code looks ok, and there's even a [socketStatus feature](https://nuxt-socket-io.netlify.app/socketStatus#example) that should capture the reconnection events.

**Comment by WhatzzUpp** [comment]
@richardeschloss "nuxt-socket-io": "^2.0.3" is installed. Actually solved this issue by listen on the "connect" event and join our chat rooms again after disconnected.
