### ISSUE TITLE
Can you provide more information on the basic example's backend server?

### ISSUE THREAD

**Issue by scalemaildev** [richardeschloss/nuxt-socket-io#270]
I am currently looking to decouple my Nuxt app's frontend from the io server. The basic example mentions that you're using CORS between netlify and the heroku app. However, I don't see any source code for the heroku app (it looks like an Express page).

If someone wanted to migrate their server, could they just copy out their server source and run it in socket.io? Or are there any differences introduced by nuxt-socket-io that would need to be accounted for? Thanks.

**Comment by richardeschloss** [comment]
This project uses a standalone script (for example: [feat/nuxt3-update](https://github.com/richardeschloss/nuxt-socket-io/blob/feat/nuxt3-update/lib/standalone.js)).  To fully decouple the socket.io server from the Nuxt app, you would instead provide your own http server instance when calling `register.server`. It's actually bare nodejs on the backend.

See also [io-server-overrides](https://nuxt-socket-io.netlify.app/configuration#io-server-overrides) to see more examples of `register.server`. The advantage of using this method is if someone had io services in their folder tree, `register.server` would still register those.
