### ISSUE TITLE
Nuxt3: Integrate with Pinia

### ISSUE THREAD

**Issue by richardeschloss** [richardeschloss/nuxt-socket-io#272]
@vsisquesc-erasmusplay do you want to help integrate this feature? I appreciate the fork!

**Comment by OyewoleOyedeji** [comment]
I would like to request this feature

**Comment by richardeschloss** [comment]
I like the idea. I plan to support it.

**Comment by richardeschloss** [comment]
Hi, there currently is a feature that may suit your needs: `ioState`. I think this is far more flexible and easier for the library to implement. In nuxt.config, I call the option "iox" (to replace the old "vuex" option)

nuxt.config:
```js
io: {
  sockets: [{
    iox: ['chatMessage --> chats/message']
  }]
}
```

In the above config, when an event "chatMessage" is received, it will be available in the internal state "$ioState":

```js
computed: {
  chatMessages() {
    return this.$ioState().value?.chats?.message // chats/messages
  }
},
```

**Comment by richardeschloss** [comment]
Closing for now because I think ioState will do most of what we want. Socket.io Events <--> ioState. We might not get actions, but not really a big deal because we can directly interact with ioState.
