### ISSUE TITLE
Use an existing socket with nuxt-socket-io

### ISSUE THREAD

**Issue by bleneauq** [richardeschloss/nuxt-socket-io#275]
Hello,
I work on a project based on WebSocket through a relay server and my problem is that when I refresh or redirect my page to www.google.com, for example, my socket is crushed and disconnected. To fix this, I thought that nuxt-socket-io was a good solution to make my socket persist. So I wondered if I could attach an existing socket to a nuxt-socket instead of creating a new one with the method this.$nuxtSocket ? 
Thank you for your help.

**Comment by richardeschloss** [comment]
Unfortunately, Websocket and Socket.io while using very similar terminology, are not interchangeable. Reference: https://socket.io/docs/v4/#what-socketio-is-not

**Comment by bleneauq** [comment]
Sorry, my mistake, I wanted to say socket.io instead of WebSocket, so is it possible to attach an existing socket.io socket to a nuxt-socket one?

**Comment by richardeschloss** [comment]
I'm not really understanding the question. Can you please provide simplified and formatted code snippets that explain what you want to accomplish?

The sockets created by Nuxt socket.io can connect to any socket.io server.

**Comment by bleneauq** [comment]
Can I explain in further detail my question to you by sharing different code snippets, etc. via your private email or other (for confidential reasons)? Thank you.

**Comment by bleneauq** [comment]
Ok no problem, I manage to use nuxt-socket-io with my project, and everything works well but now I want to make the socket persistent, in other words, when I refresh my page and redirect to another one, I don't want my socket disconnected. I try out the parameter persist in the nuxtSocket declaration but that doesn't change anything for now. Do you have an idea?

Here are my different files:

in index.vue (my main page I want to refresh without disconnect my socket) :

```
<template>
  <div>
    <div>
      <el-button @click="Open"> OPEN </el-button>
    </div>
  </div>
</template>
  
<script>

export default {
  data() {
    return {
      sessionId: '',
      socket: null,
      qr: 'dednzzndozuex', //this is an example of connection string
      keydec: null
    }
  },
  created() {
  },
  methods: {
    async Open() {
      const THIS = this
      async function onMessage(event, data) {
        console.log(`\nEvent: ${event} ${JSON.stringify(data)}`)
  
        if (event === 'connected') {
          THIS.sessionId = data.sessionId
        } 
      }
      const { query, keydec } = await this.$ConnectUser.create(
        process.env.baseUrl,
        THIS.qr,
      )

// KEYDEC is only a key for the encryption
      THIS.keydec = keydec

      THIS.socket = this.$nuxtSocket({
        persist: 'mySocket',
        name: 'connect',
        path: '/Connect',
        secure: true,
        query
      })

// HERE I attach my nuxtSocket to socket.io (see in SDK below)
      this.$ConnectUser.attachSocket(THIS.socket, keydec, onMessage)
    },
  }
}
</script>
```

in plugins/Connect.js (where I create an instance of my SDK class) :

```
import { ConnectUser, Messages, StatusPayment } from 'sdk'

class CPayUser {
  constructor() {
    this.ConnectUser = null
  }

  async create(url, uri) {
    this.ConnectUser = new ConnectUser(url, console.log)
    return this.ConnectUser.buildParameters(uri, undefined)
  }

  async attachSocket(socket, keydec, onMessage) {
    this.ConnectUser.attachSocket(socket, keydec, onMessage)
  }

}

export default ({ app }, inject) => {
  inject('ConnectUser', new CPayUser())
}
```

In nuxt.config.js :

```
io: {
    // module options
    sockets: [
      {
        name: 'connect',
        url: env.baseUrl  
      }
    ]
  },
```

And in my sdk, the 2 methods used in plugin/Connect.js and index.vue:

```
connect(uri, callback, country, userdata) {
        let { query, keydec } = this.buildParameters(uri, country, userdata)

        try {
            let socket = io.connect(this.endpoint, {
                path: '/Connect',
                secure: true,
                query,
            })

            this.attachSocket(socket, keydec, callback)

            return socket
        } catch (e) {
            if (this.logger !== null) this.logger(`Error: [${e}]`)
        }
        return null
    }

    /**
     * @desc    Attach socket to worker
     **/

    attachSocket(socket, keydec, callback) {
        try {
            let THIS = this

            // Connect
            socket.on(Messages.CONNECT, () => {
                THIS.sockets.push({
                    sessionId: null,
                    socket: socket,
                    relayPublicKey: null,
                })
            })

            // Disconnected
            socket.on(Messages.DISCONNECT, () => {
                let index = THIS.sockets.findIndex((o) => o.socket.id === socket.id)
                if (index !== -1) {
                    callback(Messages.DISCONNECT, { merchantId: THIS.sockets[index].merchantId })
                    THIS.sockets.splice(index, 1)
                }
            })

        } catch (e) {
            if (this.logger !== null) this.logger(`Error: [${e}]`)
        }
    }
```

**Comment by richardeschloss** [comment]
How are you doing the page refresh. Is it with `this.$router.go(0)` ? 

FYI, you may also want to read https://github.com/socketio/socket.io/issues/2697 . Basically, the socket.io socket instance is not serializable and can't be stored in a database, but other pieces of data can. Most likely, you may want to consider persisting that data in redis and using the [socket.io redis-adapter](https://socket.io/docs/v4/redis-adapter/). I think you're ultimately after an in-memory store when your app runs. I think that'll give you a lot of options.

**Comment by bleneauq** [comment]
No, I just do it manually. So the persist parameter in nuxtSocket can't solve this problem of my socket persistence? Or can I store the socket into vuex store for example to reuse it after disconnection?
