### ISSUE TITLE
Can I use it to emit from serverMiddleware

### ISSUE THREAD

**Issue by dword-design** [richardeschloss/nuxt-socket-io#277]
Hey, I just built my own solution and think about switching to this module. My use case is the following:

I have serverMiddlewares that define the API endpoints. They basically emit events. Then the client will register to the server and react to events.

My current solution is that I have a shared JS file with the `socket.io` server instance that is filled by a hook in the module and imported into the serverMiddleware. Is it possible to do this use case with this module?

**Comment by richardeschloss** [comment]
It's possible, but ideally you don't want to mix REST API endpoints with socket.io events. I recommend using the module's [Automatic IO Server Registration](https://nuxt-socket-io.netlify.app/configuration#automatic-io-server-registration) for handling the socket.io events.

**Comment by richardeschloss** [comment]
Usually socket.io and REST are separated, living side-by-side instead of one inside the other, because the two are their own communication protocols (some example snippet [here[(https://github.com/richardeschloss/nuxt-socket-io/issues/155#issuecomment-714810041)).

So even though socket.io technically *can* be inside a REST api endpoint, you have to hit the REST api endpoint first before emitting any socket.io events, instead of simply sending the socket.io events. Socket.io under the hood also takes care of connect / reconnect easily when the socket.io server is not inside the REST api endpoint.

My recommendation is if the two servers need to share data, they both get access to the same database and can make whatever queries they need to that shared data.

**Comment by dword-design** [comment]
Thanks for the explanation. I know this architecture roughly from [Notion](https://www.notion.so/) where they use WebSockets for website interaction and the REST API for integrations. But what if e.g. an external service manipulates data with the REST API via a PUT request (he can't access the WebSockets), how do I let the connected clients know that there were changes?

**Comment by richardeschloss** [comment]
For that specific use case, I'd probably use socket.io broadcasting to namespaces which can be done with `io.of(namespace).emit(msg)`. That `io` lives on the outerscope and not inside the REST api. 

It's possible you *may* require the use of `socket` inside a REST api endpoint, and if that's the case, I'd probably send the REST api the `socket.id` of the connected client. and then pull out the socket instance on the server from the managed map:

```js
const io  =  /* socket io server */
router.put('/someData', function({ socketId, ...args }) {
  const socket = io.of('/').sockets.get(socketId)
  // socket.emit back to client
  // socket.join namespaces etc.
})
```
I think this would make the code much cleaner and avoid extra indentation from nesting one inside the other.

**Comment by dword-design** [comment]
How would I send the `.socket.id` to the client if the API call is outside the allowed domains for the web sockets?

> ```js
> const io = /* socket io server */
> ```

How do I get the socket io server here?

**Comment by richardeschloss** [comment]
https://socket.io/docs/v4/server-api/#new-serverhttpserver-options

**Comment by dword-design** [comment]
Ah ok so I'm not using the module in this case. How would I instantiate this server in a Nuxt context? In an [example](https://github.com/nuxt/nuxt.js/blob/dev/examples/with-sockets/io/index.js) I found they wrap it around the Nuxt server in a hook, is that the way to do it?

**Comment by richardeschloss** [comment]
Considering that Nuxt3 is almost ready to be released and it's hooks are a bit different, I'd probably hook into ["listen"](https://github.com/nuxt/framework/blob/046a65fb1a9b1daaaa8a50b10d1249ff5bb26516/packages/schema/src/types/hooks.ts#L140) to piggy back off their server, like I've done [here](https://github.com/richardeschloss/nuxt-socket-io/blob/c402b1491498add86fddc22cdc0acf62599c244f/lib/module.js#L206). However, I remember having issues with the listen hook providing me what I wanted a few months ago, but maybe things are different now.

There might be an argument for separating out the socket.io server from the Nuxt server, I found this approach easier to maintain the socket.io server-side logic, and make it framework-agnostic. 

But for sake of argument, going back to the question, you have several options:

1. Add [server middleware](https://nuxtjs.org/docs/configuration-glossary/configuration-servermiddleware), and share the `io` instance.

In your module:
```js
/* imports */
export default function () {
  let io // Share io instance
  this.addServerMiddleware({
    path: '/api/someEnpoint',
    handler(req, res, next) {
      io.to('/').emit('broadcasted event', { msg: 'some data' } )
    }
  })
  this.nuxt.hook('render:before', (renderer) => {
    const server = http.createServer(this.nuxt.renderer.app)
    io = socketIO(server)
    io
     .of('/someChannel')
     .on('connection', (socket) => { /* work with socket events here */ }
  })
```

2. In Nuxt2, it may be easier to have your server be the thing that starts up both Nuxt and socket.io, as in this [example](https://github.com/nuxt/nuxt.js/blob/dev/examples/with-sockets/server.js). But note, in Nuxt3, they separate out the server into Nitro, and this approach isn't as easy (to start the server programmatically).

---

On a side note, I was going to also recommend http2 push, but I just found out that [Chrome will remove it](https://developer.chrome.com/blog/removing-push/)...

**Comment by dword-design** [comment]
Ok great thanks for the useful elaborations! I was thinking if I can still use nuxt-socket-io but looks like it's easiest do spin up the io server myself. I think it would be helpful for the module to export the io server so it can be imported elsewhere.

**Comment by richardeschloss** [comment]
It already does. https://nuxt-socket-io.netlify.app/configuration#io-server-overrides

```js
import http from 'http'
import { register } from 'nuxt-socket-io'

// Options can be host, port, ioSvc, nspDir:
const myIOServer = register.server({ port: 3001 }) // your IO server, to start http server, listening on 3001

// You can also provide your own server instance if you want:
const httpServer = http.createServer()
const myIOServer2 = register.server({ port: 3002 }, httpServer) // use your server instead
```
