### ISSUE TITLE
Stopped working on nuxt 3

### ISSUE THREAD

**Issue by luabraggion** [richardeschloss/nuxt-socket-io#278]
![Captura de tela 2022-10-17 183941](https://user-images.githubusercontent.com/77340549/196289792-a99ebcf7-5237-4346-9d1a-cdad45516e57.png)

after updating nuxt 3 it started to give this error.

**Comment by richardeschloss** [comment]
What version of nuxt-socket-io are you using?

**Comment by luabraggion** [comment]
I'm currently using ^3.0.9 but I've already tested 3.0.6 to 2 all with the same error, but it was working started with this error after I updated nuxt, I ran the command npx nuxi upgrade -f

**Comment by minesettimi** [comment]
had this error with the listen hook before, the server given by the hook needs to be defined for typescript

**Comment by richardeschloss** [comment]
@minesettimi do you a fix on your end?

**Comment by richardeschloss** [comment]
Fwiw, the last version I tested this on was nuxt3 "3.0.0-rc.3-27550969.a4a3cff", back in May 2022. The part where I believe the code is error'ing out is here: 

https://github.com/richardeschloss/nuxt-socket-io/blob/773d9d49c54e8dbe090c43855e8b8bf3f204dbb1/lib/module.js#L14

This should be valid if socket.io 4.x is installed.

**Comment by luabraggion** [comment]
I installed the version of socket.io@latest which is in 4.5.3 but it still gives an error, the weirdest thing was that I just updated nuxt started with this error, and this application is in production I need socket.io

**Comment by Thomas487** [comment]
I'm also experiencing the same issue.
> ERROR  Cannot start nuxt:  Cannot destructure property 'Server' of '_engineIo.default' as it is undefined.

Currently running nuxt on `3.0.0-rc.12-27736489.2e080c2`
with the following dependencies:
`nuxt-socket-io^3.0.9` `socket.io^4.5.3`

@luabraggion did you find a workaround?

**Comment by luabraggion** [comment]
@Thomas487 still none, I disabled socket.io in nuxt config for now to be able to run the project, but I need to find an urgent solution the project is already in prod and I need socket.io working, I tried to go back to the previous version of nuxt but no I achieved.

**Comment by Thomas487** [comment]
@luabraggion I got it working by reverting to socket.io^4.1.1, as specified in the dependencies, however there are a few vulnerabilities so i would not recommend it for a site in production.

**Comment by minesettimi** [comment]
it seems to work in version 4.5.2 of socket io just fine, it seems to be an issue with the latest version of 4.5.3

**Comment by richardeschloss** [comment]
@luabraggion will 4.5.2 work for you? The [Changelog](https://github.com/socketio/socket.io/blob/main/CHANGELOG.md#453-2022-10-15) from 4.5.2 to 4.5.3 seems minor if you're not using http2.

**Comment by luabraggion** [comment]
it still doesn't work for me I tried to install the socket version 4.1.1 and 4.5.2 but when I start nuxt it still gives an error.

**Comment by luabraggion** [comment]
![Captura de tela 2022-10-18 130437](https://user-images.githubusercontent.com/77340549/196483850-5af85541-2044-489b-9609-03a83d16c646.png)

**Comment by richardeschloss** [comment]
I just pushed an update to github nuxt3-update branch. socket.io LTS (4.5.3) + nuxt3 3.0.0-rc.3-27550969.a4a3cff works. I'll try updating nuxt3 now

**Comment by richardeschloss** [comment]
Ok, something about nuxt3 latest broke it. 
Broken ---> Nuxt 3.0.0-rc.12-27768618.05fd222 with Nitro 0.6.0-27768582.4603279
Works / workaround --> 3.0.0-rc.3-27550969.a4a3cff

I'll need to spend more time to figure out why it's broken later. I have other obligations that require my attention at the moment.

**Comment by minesettimi** [comment]
3.0.0-rc.11 with nitro 0.5.4

**Comment by richardeschloss** [comment]
Ok, I'm able to get everything working with latest stable version by updating engine.io's wrapper. 
A workaround today would be inside node_modules/engine.io/wrapper.mjs:
```js
import * as lib from "./build/engine.io.js"; // <-- replace the first line with this
import lib from "./build/engine.io.js"; // <-- broken. It doesn't seem as though engine.io export's a default.
```

**Comment by Gruce** [comment]
Facing the same issue with
`Nuxt 3.0.0-rc.13-27772354.a0a59e2` with `Nitro 0.6.1-27772346.484261a `

**Comment by richardeschloss** [comment]
FWIW, I just verified it works with: socket.io 4.1.1 and nuxt3 rc11 [my package.json](https://github.com/richardeschloss/nuxt-socket-io/blob/7f809af2527d4a542c63d0206d382a2a9715e232/package.json#L63). I'll try bumping up the deps.

**Comment by jjazzme** [comment]
> Ok, I'm able to get everything working with **latest stable version** (nuxt3-rc.12, socket.io 4.5.3) by updating engine.io's wrapper. A workaround today would be inside [node_modules/engine.io/wrapper.mjs](https://github.com/socketio/engine.io/blob/917d1d29e13f2e8f523c3738f6413f67b587aebe/wrapper.mjs#L1):
> 
> ```js
> import * as lib from "./build/engine.io.js"; // <-- replace the first line with this
> import lib from "./build/engine.io.js"; // <-- broken. It doesn't seem as though engine.io exports a default.
> ```
> 
> For some reason, I can run "node ./lib/module.js" which imports from socket.io and I have no issue. It's only when I run Nuxt that it complains about the import.

work for me

**Comment by go4cas** [comment]
I have managed to get the socket server running using `nuxt-socket-io@nuxt3rc` (3.0.9), but I have a few questions:

1. Where/how inside `next.config.ts` do I add the cors config?
2. How do I access the `io` instance from within `/server/api` endpoints?

**Comment by richardeschloss** [comment]
Deleted the comment because:
1. It was beyond the scope of the original issue. 
2. Did not show enough effort. The question has been answered.

**Comment by richardeschloss** [comment]
Ok, I just released nuxt-socket-io@3.0.10 to at least get some kind of support for Nuxt3. it's based on 4.1.1 since that has been proven to work. As the issues get ironed out, I'll update that dep to socket.io LTS. In the meantime, things should work out-of-the-box now, and for those who absolutely need 4.5.3, please consider the workaround above for now.

**Comment by bnbc** [comment]
Hello, maybe i didn't understand the resolution of this issue but i still have the same error `Cannot destructure property 'Server' of '_engineIo.default' as it is undefined.` with nuxt 3.0.0 and nuxt-socket-io 3.0.10.

I start a new nuxt3 project with `npx nuxi init <project-name>`

My package.json

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0"
  },
  "dependencies": {
    "nuxt-socket-io": "3.0.10"
  }
}
```

The error append when i launch `yarn install`

Thks for your time and works !

**Comment by richardeschloss** [comment]
What version of socket.io got installed?

**Comment by bnbc** [comment]
In node_modules/socket.io it's 4.5.4, but i also try to install 4.1.1 with this package.json and get same error.
I delete node_modules and .nuxt folder before make a yarn install again.

````
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0"
  },
  "dependencies": {
    "socket.io": "4.1.1",
    "socket.io-client": "4.1.1",
    "nuxt-socket-io": "3.0.10"
  }
}
```

**Comment by richardeschloss** [comment]
I see what happened. My package deps accidentally included the "^" before the 4.1.1. which will install the newer version. Clamping it to 4.1.1 should work (it worked for me). I can double-check

**Comment by bnbc** [comment]
Ok seems to work now with the same package.json, i just use npm install and npm run dev instead of yarn.

And now when i do with yarn it's ok too... so strange... thks !

**Comment by richardeschloss** [comment]
Ok, just curious, what version of yarn is it?

**Comment by bnbc** [comment]
yarn 1.22.19

I reproduce the issue to be sure.

On new project with my package.json : `yarn install` causes the error, `npm install` is ok...
