### ISSUE TITLE
Importing module causing nuxt fatal error

### ISSUE THREAD

**Issue by Bryt12** [richardeschloss/nuxt-socket-io#279]
Hello, when adding nuxt-socket-io to my project I am getting a fatal error when I run 

`yarn dev`

<img width="959" alt="Screenshot 2022-12-01 at 2 06 37 PM" src="https://user-images.githubusercontent.com/8965979/205138514-eae33129-9139-4941-9577-5547aed283f9.png">

So logically I install @nuxt/kit and received a new fatal error

<img width="816" alt="Screenshot 2022-12-01 at 2 07 08 PM" src="https://user-images.githubusercontent.com/8965979/205138622-b35b24d1-0dda-4a20-8098-6b9cb6fd69ef.png">

### Package versions:
Nuxt: ^2.15.8
nuxt-socket-io: ^3.0.10
node -v: v16.14.0

### Steps to reproduce
1.
`yarn create nuxt-app lightweight`

2.
`yarn add nuxt-socket-io`

3.
nuxt.config.js:

`{ modules: ["nuxt-socket-io"] }`

4.
`yarn dev`

Thank you!

Edit: Running MacOS 13.0

**Comment by richardeschloss** [comment]
nuxt-socket-io by default will now support the Nuxt3 release which is now stable. To get nuxt-socket-io, it should be installed with: 

> yarn add nuxt-socket-io@2

**Comment by Bryt12** [comment]
Yup, that resolved the issue, thank you so much for the quick response!
