### ISSUE TITLE
How to use nuxt-socket-io to broadcast?

### ISSUE THREAD

**Issue by timstrasser** [richardeschloss/nuxt-socket-io#280]
Hello,
I'd like to use nuxt-socket-io to receive message from the clients and broadcast them to all other clients. However, I'm a bit overwhelmed by the configuration documentation and not sure how to configure my project accordingly.

I'd basically like to have something equivalent to this:
```js 
socket.on('sentMessage', function message(data: IMessage) {
  socket.broadcast.emit('newMessage', data);
});
```

**Comment by richardeschloss** [comment]
https://socket.io/docs/v4/#broadcasting

So on the server-side, you'll already have `socket` and `io`. `io` is what you need to broadcast to all

```js
// to all connected clients
io.emit("hello");

// to all connected clients in the "news" room
io.to("news").emit("hello");
```
