### ISSUE TITLE
emitBack registration failure

### ISSUE THREAD

**Issue by jstrother** [richardeschloss/nuxt-socket-io#35]
Hello-

I am getting the following error:
```
Error: [nuxt-socket-io]: Trying to register emitback titleFromUser failed
because it is not defined in Vuex.
Is state set up correctly in your stores folder?
```
Yet, I am sure I have followed your examples. Below are the appropriate snippets of the code in question:

```nuxt.config.js```
```
...
modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@nuxtjs/auth',
    'nuxt-socket-io',
  ],
  io: {
    sockets: [
      {
        name: 'index',
        url: 'http://localhost:3000',
        default: true,
        vuex: {
          mutations: [{ newTitles: 'SET_NEW_TITLES' }],
          actions: [],
          emitBacks: ['titleFromUser'],
        },
      },
    ],
  },
...
```
```store/index.js```
```
...
export const state = () => ({
  titleFromUser: '',
  newTitles: [],
});
...
```
```pages/index.vue```
```
...
<script>
import { mapState } from 'vuex';

export default {
  components: {},
  data() {
    return {
      titleFromUser: '',
    };
  },
  computed: mapState(['newTitles']),
  mounted() {
    this.socket = this.$nuxtSocket({
      channel: '/index',
      reconnection: false,
    });
  },
  methods: {
    submit() {
      this.$store.commit('SET_TITLE_FROM_USER', this.titleFromUser);
    },
  },
};
</script>
...
```
Before the error in my console, I am getting ```connect index http://localhost:3000/index```, so I know it's connecting, but I'm not sure why the ```emitBacks``` is failing.

Thanks for taking a look.

**Comment by richardeschloss** [comment]
Hi! Thanks for bringing this to my attention! I'll have a look at it right now.

**Comment by richardeschloss** [comment]
ok, fix is coming. I see what happened. an empty string was causing the plugin to misinterpret that as undefined. I put the proper checks in now. Just re-running tests to make sure no regressions are coming.

**Comment by richardeschloss** [comment]
v1.0.8 pushed with the fix.

**Comment by jstrother** [comment]
Thanks for the quick response! Working as expected now. :)
