### ISSUE TITLE
This dependency was not found * @/io/plugin.utils in ./.nuxt/nuxt-socket-io.js    

### ISSUE THREAD

**Issue by matamune94** [richardeschloss/nuxt-socket-io#45]
How fix this bug ?

**Comment by richardeschloss** [comment]
Looking into it right now.

**Comment by richardeschloss** [comment]
It seems like Nuxt was not including it when it built the plugin. The plugin utils are in `nuxt-socket-io/io/plugin.utils.js`, but I'm going to fix this by just including the utils back in the file. Issue is fixed in #46 . v1.0.12 deployed with the fix.
