### ISSUE TITLE
Help requested: vuex mutations on listen events

### ISSUE THREAD

**Issue by mcbloch** [richardeschloss/nuxt-socket-io#49]
I'm trying to puzzel together a simple application with 1 websocket server and 2 mutation functions. 
One of them is a broadcast event and is not arriving in my nuxt frontend, whilst it is arriving in another mini client.
The mutation function registered in the nuxt.config.js file is not called and i'm clueless how to debug such an issue.

Is there the possibility to log all incoming events, registered or not? Is there another way to debug on a lower level?

**Comment by richardeschloss** [comment]
I like the logging idea! Lemme think about how to configure it cleanly.
There'd be log event and possibly the log level (debug, error, info, warn,
and even time duration, like console.time)

**Comment by richardeschloss** [comment]
I promise on Saturday or Sunday I'll be more helpful! My computer is not
with me at the moment.

**Comment by richardeschloss** [comment]
NustSocket needs to be instantiated on at least one page or component to
register the mutations.

**Comment by mcbloch** [comment]
My other mutation is correctly called by the module which means that I instantiated it correctly in my component. It's so odd because I use them exactly in the same way.

**nuxt.config.js**
```
modules: [
    'nuxt-socket-io'
  ],
io: {
    sockets: [
      {
        name: 'home',
        url: 'http://localhost:5000',
        default: true,
        vuex: {
          // optional
          mutations: [
            { sync_one: 'nsv/set_data_one', sync_two: 'nsv/set_data_two' }
          ]
        }
      }
    ]
  },
```

**nsv.js**
```
export const mutations = {
  set_data_one(state, data) {
    console.log('data one')
  },
  set_data_two(state, data) {
    console.log('data two')
  }
}
```

**MyComponent.vue**
```
...
mounted() {
    this.socket = this.$nuxtSocket({
      name: '',
      channel: '/',
      reconnection: false
    })
  }
```
I'll try to debug it by slimming the server down to the bare minimal for this example.

A logging event would be nice to have :+1: , let me know when you have some more information!

**Comment by richardeschloss** [comment]
For now, if you want, in nuxt-socket-io/io/plugin.js you can put a
console.log statement in the register.vuexListeners method

**Comment by richardeschloss** [comment]
Can you also please provide the code snippet on your server that is sending
the events? I think I'll be able to look at it tonight.

**Comment by mcbloch** [comment]
I boiled it down to 1 python file.
Also included my virtual environment dependencies (python3.8)

I used this server together with the nuxt code i send earlier in this issue.
The client prints 'data one' once and nothing else.

**app.py**
```python
from gevent import monkey

monkey.patch_all()

from apscheduler.schedulers.gevent import GeventScheduler

from typing import NoReturn

from flask import Flask
from flask_socketio import SocketIO


def create_app():
    app = Flask(__name__)

    @app.route("/")
    def hello_world():
        return "Hello world"

    socketio = SocketIO(app, cors_allowed_origins="*", logger=True)

    def sync_recurring():
        socketio.emit('sync_two', {"other key": "other value"}, room=None)

    @socketio.on("connect")
    def connect_sync():
        socketio.emit("sync_one", {
            "some key": "some value"
        })

    sched = GeventScheduler()
    sched.add_job(sync_recurring, 'interval', seconds=2)
    sched.start()

    return app, socketio


def main() -> NoReturn:
    app, socketio = create_app()
    socketio.run(app, host='localhost', port=5000)


if __name__ == "__main__":
    main()
```

**requirements.txt**
```
APScheduler==3.6.3
Click==7.0
Flask==1.1.1
Flask-SocketIO==4.2.1
gevent==1.4.0
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10.3
MarkupSafe==1.1.1
python-engineio==3.11.2
python-socketio==4.4.0
pytz==2019.3
six==1.13.0
tzlocal==2.0.0
Werkzeug==0.16.0
```

**Comment by richardeschloss** [comment]
Ok, I'm looking into this right now. For the time being, I renamed the title to make it about the vuex mutations on broadcasted events. The logging feature will part of a separate issue.

**Comment by richardeschloss** [comment]
@mcbloch I believe the issue is:
```
vuex: {
  mutations: [
    { sync_one: 'nsv/set_data_one', sync_two: 'nsv/set_data_two' }
  ]
}
```

should be:
```
vuex: {
  mutations: [ // array of objects
    { sync_one: 'nsv/set_data_one' }, { sync_two: 'nsv/set_data_two' }
  ]
}
```

**Comment by mcbloch** [comment]
Thanks so much. That is indeed the issue. What a sily mistake of me.
