### ISSUE TITLE
Feature request: Re-use socket across components

### ISSUE THREAD

**Issue by golubvladimir** [richardeschloss/nuxt-socket-io#51]
I config socket in nuxt.config.

```
io: {
    sockets: [
      {
        name: 'users',
        url: 'http://localhost:3001',
        default: true,
        vuex: {
          mutations: [
            {block_item: 'users/blockEditUser'},
            {open_item: 'users/openEditUser'},
            {edit_item: 'users/editUser'},
            {delete_item: 'users/deleteUser'}
          ]
        }
      }
    ]
  },
```

I created two sockets in two diffent components on one page.

com 1
```
    mounted() {
      this.socket = this.$nuxtSocket({
        name: 'users',
        channel: '/',
        reconnection: true
      });
    }
```
com 2
```
      this.socket = this.$nuxtSocket({
        name: 'users',
        channel: '/',
        reconnection: true
      });
```

I move to this page, get it in console.
```
  nsp.on('connection', socket => {
    console.log('connect');
    console.log(socket.id);
```
```
connect
jskBtZ1CDysNE27FAAAA
connect
o6qBrU8oXucjM7DvAAAB
```

How to create one socket, expect pass by props from page component ?

**Comment by golubvladimir** [comment]
Can I send emit on action ?
```
          actions: [
            {'users/deleteUser': 'test_action'}
          ]
```

**Comment by golubvladimir** [comment]
It don't work.
```
          mutations: [
            {block_item: 'users/blockEditUser'},
            {open_item: 'users/openEditUser'},
            {edit_item: 'users/editUser'},
            {delete_item: 'users/deleteUser'},
            'test_action <-- users/testAction'
          ],
```

**Comment by golubvladimir** [comment]
It don't work.
```
emitBack: [{'users/selectUser': 'test_action'}]
```

**Comment by golubvladimir** [comment]
Is it possible to send an emit by action or mutation ?

**Comment by richardeschloss** [comment]
To answer the question (issue's title), the socket.io server joins the two together with `socket.join`. Join is not available in the underlying socket.io-client. Please see the chat rooms example on the server side to see how sockets can join specific namespaces. 

Example code might look like
```
socket.on('joinNsp', ( user) => { // In IO server
  const namespace = `usersNsp`
  socket.join(namespace, () => {
    // client joined namespace
   const info = { namespace, id: socket.id }
   socket.emit('userJoined', info) // This echos the event back to this client
   socket.to(namespace).emit('userJoined', info) // Send event to others in the namespace; does not echo back to the client it received this event from
  })
})
```

As you mentionned, you should also be able to pass in the socket io client as a prop (I think). Each time a new socket io client is instantiated, it's treated as a separate client, even if it's in the same application. However, I think joining the clients and using a common namespace will result in far cleaner code.

**Comment by richardeschloss** [comment]
> Is it possible to send an emit by action or mutation ?

In the current state of software, vuexOptions "mutations" and "actions" only get triggered on events that are received (listened to). The vuexOptions "emitBacks" will emit back property changes in the vuex state, not the actions; I think this also results in cleaner and less code for the developer. If it is desired to have a vuex action emit an event, the current way to do it is to use socket.io-client directly, which is packaged with this plugin. I can try to think about how an action would be configured as an emitter in nuxt.config, but I'm afraid implementing that would require me to do something in a non-Nuxt way and potentially break dev's code.

**Comment by richardeschloss** [comment]
The other issue brought was a completely separate from the issue opened here, and belonged in its own issue, so I moved it to its own issue #56. 

See also: [CONTRIBUTING.md](https://github.com/richardeschloss/nuxt-socket-io/blob/gh-pages/CONTRIBUTING.md)

**Comment by richardeschloss** [comment]
I'm thinking perhaps the implementation could be something like:
```
// Component 1:
this.socket1 = this.$nuxtSocket({ channel: '/', reuse: true })

// Component 2:
this.socket2 = this.$nuxtSocket({ channel: '/', reuse: true })

// if reuse is true, then we would expect:
this.socket1.id === this.socket2.id
```

The implication of this, however, is that that closing the socket would be the responsibility of the developer. I.e., in the Vue `beforeDestroy` or `destroy` lifecycle hooks, the developer would be responsible for calling `if (this.socket1.connected) this.socket1.close()`.  (Normally, the plugin would handle this teardown, but this would become the responsibility of the deveoper)

**Comment by richardeschloss** [comment]
The more I think about it, I think the previous suggestions are better. I think it's cleaner design to have each component have its own socket; i.e., each component has its own ears and mouth. I think I'll close this issue for now, and may consider re-opening it.
