### ISSUE TITLE
Question: Is it possible for emitBacks to watch and emitBack entire objects?

### ISSUE THREAD

**Issue by golubvladimir** [richardeschloss/nuxt-socket-io#54]
When I define param as object, I have an error.
When I define param as string, I dont't have an error.

```
export const state = () => ({
  userForChange: {}
});
```
```
 emitBacks: [
  {'users/userForChange': 'open_modal'},
```

**Comment by golubvladimir** [comment]
Solved the problem by JSON.stringfy and JSON.parse server. Maybe is there a better solution ?

**Comment by richardeschloss** [comment]
Hi, thanks for bringing up this concern! I'll look into this soon. I think the issue might be with vuex `this.$store.watch` (I think it only watches primitive properties?).

**Comment by richardeschloss** [comment]
PR #57 created.
