### ISSUE TITLE
Consider implementing a debug logging feature

### ISSUE THREAD

**Issue by richardeschloss** [richardeschloss/nuxt-socket-io#55]
I'm thinking debugging would be enabled if a specific environment variable is set:
For example:
> DEBUG="io" npm run dev

might allow the logging of io events to the console.

**Comment by richardeschloss** [comment]
FYI @mcbloch , would this implementation suit your needs? Debug logging would only be enabled if the environment varable is defined and set to "io".

**Comment by mcbloch** [comment]
That would be very much okay.
I don't know if you use 'DEBUG' just as example or if you are planning to use that keyword, but I would suggest something more specific to avoid collisions. Something like 'NUXT_SOCKETIO_DEBUG=true'.

Otherwise if another module needs the 'DEBUG' keyword you have to choose and can't combine.

**Comment by richardeschloss** [comment]
Some helpful news I just learned about. Socket.io *already* has debug logging feature built into it, and I think their implementation is easier than what I can create. The feature is described [here](https://socket.io/docs/logging-and-debugging/).

So, to debug in:
*  the *browser*, simply set `localStorage.debug = '*'`
*  NodeJS, simply set `DEBUG='*'`

Under the hood, it uses the [`debug`](https://github.com/visionmedia/debug) node module which is the module I was going to use anyway. The above debug statements can get a bit verbose, so to only look at specific scopes, it's just a matter of updating the variable:

> `localStorage.debug = socket.io-client:socket` // Debug only client-side IO in browser

Just remember to not ship production code with those statements! ;) 

--- 

I guess I *could* implement some debugging to log when io config gets registered, but I think most people that use the plugin will debug IO events more than the config. (I'll think about it)

**Comment by richardeschloss** [comment]
PR #58 created with debug logging feature. Should make life easier.
> localStorage.debug = 'nuxt-socket-io' // Debug just the plugin

> localStorage.debug = 'nuxt-socket-io, socket.io-client:socket' // Debug even more (socket.io-client logs too)
