### ISSUE TITLE
How to shut off warnings in console ?

### ISSUE THREAD

**Issue by golubvladimir** [richardeschloss/nuxt-socket-io#63]
How to shut off warnings in console ? 

```
users/userForDelete is an object. You probably want to watch its properties instead
```

Something like:
```
{
  debug: false
}
```

**Comment by richardeschloss** [comment]
I think doing it in Chrome dev tools is even easier:
![Screenshot from 2020-02-06 12-52-14](https://user-images.githubusercontent.com/5906351/73973433-c77d3580-48df-11ea-809b-6746a93eca2b.png)

If the warnings were made an option, then we'd have to rebuild the Nuxt app for the setting to take effect. This way, it can show/hide the warnings in the console right away.

**Comment by richardeschloss** [comment]
For the specific warning you reference, I can check to see if it's still worth warning about.

**Comment by richardeschloss** [comment]
Ok, I think I'll remove that one warning. I think the other warnings should stay in there to prevent the developer from shooting himself in the foot. Those other warnings will only be present until they are resolved.

**Comment by richardeschloss** [comment]
PR #64 merged. The disable feature will be in nuxt.config:
```
io: {
  warnings: false, // disable warnings
  sockets: [...]
}
```

**Comment by richardeschloss** [comment]
v1.0.16 pushed to npm.
