### ISSUE TITLE
Can't connect to server on subdirectory

### ISSUE THREAD

**Issue by osayfun** [richardeschloss/nuxt-socket-io#67]
I can't connect to my server located on subdirectory `http://somedomain.com/example`.
How can this be achieved?

**Comment by richardeschloss** [comment]
This issue does not provide enough details in order for me to help you and does not respect the contributing guidelines. Please see [CONTRIBUTING.md](https://github.com/richardeschloss/nuxt-socket-io/blob/master/CONTRIBUTING.md).

Details on how to setup Socket.IO server are [here](https://socket.io/docs/server-api/). 

Details on how to configure this plugin are [here](https://github.com/richardeschloss/nuxt-socket-io/blob/master/README.md).
