### ISSUE TITLE
Emit right after connection

### ISSUE THREAD

**Issue by benben994** [richardeschloss/nuxt-socket-io#71]
```
this.socket = this.$nuxtSocket({ 
    name: 'messenger', 
    channel: '',
    reconnection: false
})
this.socket.on('connect', () => {
    console.log('connect') // --> is printed
    this.socket.emit('snapshot', { user_id: this.userId }).on('getSnapShot', res => {
      this.getSnapshot(res)
    })
})
```
I've try above code but I can't see socket emit in Chrome dev tool.
But if I add delay like setTimeout wrapping `setTimeout(() => { this.socket.emit...}, 5000)`, the emit is definitely working.
I've checked the example, which emit event using button click, not right after connection.
Hoping someone can point me out, thanks!

**Comment by richardeschloss** [comment]
Please use the callback built in to the emitter and let me know if that helps:
 ```
this.socket.emit('snapshot', { user_id: this.userId }, res => {
  this.getSnapshot(res)
})
```

**Comment by richardeschloss** [comment]
I'm not able to reproduce this problem. I recreated the exact same code and it works. To debug the IO events, please also set `socket.io-client:socket` in localStorage to see the events being emitted.

**Comment by benben994** [comment]
Hi, I think I've using it wrong way...
`
getMeetingRoom(){
      this.socket2.emit('getMeetingRoom', { room: 'media1337' }, (resp) => {
        this.messageRxd = resp
      })
      .on('someData', handleSomeData)
    }
`
At first, I followed the documentation above but wasn't working. But I worked it out with adding this.socket.on
`
this.socket.on('someData', handleSomeData)
`

**Comment by benben994** [comment]
Hi again, I've been stuck in emit/on between server and client.
First of all, I can `this.socket.emit('snapshot')` and then receive some data with `this.socket.on('getSnapshot')`.
But I can't receive by `this.socket.on('getHistoryMessage')` after `this.socket.emit('join')` on client side (nuxt).
I had printed log on the server side, the server had received 'join' and emit 'getHistoryMessage'.
I've looking into the documentation, but can't find much about where or when to emit/on events.

**Comment by richardeschloss** [comment]
Glad you were able to get it working. Please remember to format your code using three backticks (```) instead of one to improve the readability of the code, and to improve my ability to in turn help you.
