### ISSUE TITLE
Issue: connecting to configured url does not work as expected

### ISSUE THREAD

**Issue by jd1378** [richardeschloss/nuxt-socket-io#73]
Lets say I have this config:
```
 io: {
    sockets: [
      {
        name: 'stock',
        url: `http://localhost:3000/ws/`,
        default: true,
        vuex: {
          actions: [
            {
              stockUpdate: 'product/stockUpdate'
            }
          ]
        }
      }
    ]
  },
```
the url the client should try to connect should be `http://localhost:3000/ws/` , while now it completely ignores any path after base url and instead tries to connect to `http://localhost:3000/socket.io/`

**Comment by richardeschloss** [comment]
The url should be the base url: "http://localhost:3000" since the server is hosted there. The underlying socket.io-client needs that. But then, on the io server, you need to specify a "/ws" namespace:

```
io
.of('/ws')
.on('connection', (socket) => {
  // work with socket
})
```

Then, back in your client, specify the namespace (a.k.a. "channel") when you instantiate your nuxt socket client:
```
this.socket = this.$nuxtSocket({ channel: '/ws' })
```

**Comment by jd1378** [comment]
well , the problem is that my socket server is not hosted at the baseurl of `http://localhost:3000/`

lets say I have an nginx server on `https://domain.com` that proxy pass `/api/` to `http://localhost:8000/` , `/` to `http://localhost:3000/` , and `/ws/` to `http://localhost:4000/`,
then the socket is not served at `http://localhost:3000` but actually `http://localhost:3000/ws/` ?
am I missing something ?

**Comment by richardeschloss** [comment]
where is your socket IO server?

**Comment by jd1378** [comment]
The socket io is served at `domain.com/ws/`, so the request urls should look like `https://domain.com/ws/namespace` i think.
but then after looking at socket io documents and after writing around 20 minutes to explain the issue , i realized something (sorry about the late reply). I think the solution would be to use `path` option on nuxt module (since the path is 'socket.io' by default , I did a workaround by serving socket server at domain.com/socket.io/ ).
does this module allow to pass `path` option to socket.io-client ?

**Comment by jd1378** [comment]
So what I'm saying right now is that `url` configuration **is** doing what it should do , and the thing I'm trying to achieve is by using the `path` option of socket.io-client (It's no longer an issue, but a feature request)

**Comment by richardeschloss** [comment]
It should work. I pass in all the other arguments to socket.io-client

**Comment by jd1378** [comment]
It would be good if you add a note on the Readme page as well about passing the other arguments to socket.io-client
I'll try it out soon and report the results

**Comment by richardeschloss** [comment]
My apologies, I thought I had that in the docs. I can update.

**Comment by jd1378** [comment]
I tried setting path like this but didn't work (still tries to connect to '/socket.io/), am I doing it wrong ? 
```
io: {
    sockets: [
      {
        name: 'stock',
        url: `${process.env.SOCKET_URL || domain}`,
        default: true,
        path: '/ws/',
        vuex: {
          actions: [
            {
              stockUpdate: 'product/stockUpdate'
            }
          ]
        }
      }
    ]
  },
```

**Comment by jd1378** [comment]
I made a quick limited case here (no socket server) : https://uofm3.sse.codesandbox.io/
you can check the nuxt.config.js and the url its trying to connect in dev tools
i have set the path to `/ws/` there as well but still tries to connect to `/socket.io/`
[![Edit nuxt-socket-io-test](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nuxt-socket-io-test-uofm3?fontsize=14&hidenavigation=1&theme=dark)

**Comment by jd1378** [comment]
I'm sorry, I should actually try to use path when instantiating the socket , I tried and it worked there perfectly.
I'm closing the issue now as i think it's resolved. thank you

**Comment by richardeschloss** [comment]
Glad to hear you got it working. I'll try to think about the lessons learned here so I can summarize in a simple paragraph for the readme.md docs.
