### ISSUE TITLE
Question: Is $nuxtSocket available in app context?

### ISSUE THREAD

**Issue by jd1378** [richardeschloss/nuxt-socket-io#76]
I want to know if it's possible to instantiate the socket page/component independent ?
like inside a plugin so it connect as soon as possible (or if there be an option for this would be even better, since the vuex store usage is not related to page or component) ?
I ask because i saw this which may make it not possible ? 

> ... by defining the property `socketStatus` on the same component that instantiates nuxtSocket. The plugin will then automatically set that status ...

**Comment by richardeschloss** [comment]
Yes, $nuxtSocket is injected into the app context. You can use `this.$nuxtSocket` throughout your app.

[Issue 62](https://github.com/richardeschloss/nuxt-socket-io/issues/62) has details on how you can store a socket *instance* inside Vuex to be re-used.  However, wherever nuxtSocket gets instantiated, the developer must remember to disable the auto-teardown feature, as described in the docs and that issue.

I'm a bit confused on the question surrounding the quoted text. Basically, if $nuxtSocket shares the same context as `socketStatus`, i.e., `this.$nuxtSocket` created in the same place that `this.socketStatus` is defined, the status will be filled there.

**Comment by jd1378** [comment]
thank you for reply

about the quote, my concern was this case:
when setting `let socket = ctx.$nuxtSocket({ emitErrorsProp: 'myEmitErrors' })` inside a plugin where no data exists, what will the plugin try to do ? will some kind of unexpected error happen ?
which now i think was a silly question since why would anyone do that anyway

but regarding my use case
the issue you mentioned is slightly different from what i want to achieve,
instead of instantiating when a specific page is loaded, I want to always instantiate a socket and keep it forever (till the browser tab dies) whenever the Nuxt itself is loaded, and thus a configuration for this would be handy for such use cases i think, although it is easy to create a plugin and do it manually, but using a config is more convenient
