### ISSUE TITLE
Question: How can transpile for IE 10, IE 11?

### ISSUE THREAD

**Issue by Timothy-Y-H-Lee** [richardeschloss/nuxt-socket-io#77]
Hi, Richard Schloss.
Thank you for your answers to my questions.

Recently, I need to transpile for IE 10, IE 11.
I've tried as below but didn't work.

nuxt.config.js:
````
export default {
  build: {
    transpile: [
      'nuxt-socket-io'
    ]
  }
}
````

I've been trying to solve this problem another way as below but doesn't work.

package.json :
````
{
  "scripts:": {
    "browserslist": "browserslist"
  },
  "browserslist": [
    "defaults",
    "IE >= 10"
  ]
}
````
So, could you help me out?

Thanks,

Timothy.

**Comment by richardeschloss** [comment]
I can try it out later on IE11 and Microsoft Edge. I'm less familiar with those browsers. Does your code build for Microsoft Edge?

**Comment by Timothy-Y-H-Lee** [comment]
No, I've built my codes for Chrome.
Recently, I've tested for IE11. I've realized my codes didn't work.

Thank you for your cooperation.

**Comment by richardeschloss** [comment]
Is it ok if I close the issue? Do I need to troubleshoot?

**Comment by Timothy-Y-H-Lee** [comment]
I'm closing the issue now.
Thank you for everything.
