### ISSUE TITLE
Feature request: URL should default to window.location

### ISSUE THREAD

**Issue by jd1378** [richardeschloss/nuxt-socket-io#93]
Hi
It seems the `socket.io` should using `window.location` as default url if not defined, but it seems we cannot do that with nuxt-socket-io
can you take a look ?

**Comment by richardeschloss** [comment]
Hi,

Great suggestion! You are correct, socket.io-client defaults to window.location, as I see in [io-url-opts](https://socket.io/docs/client-api/#io-url-options)

Let me take a look at it. Currently in the plugin, this line will throw an error if url is not specified:

[plugin.js](https://github.com/richardeschloss/nuxt-socket-io/blob/master/io/plugin.js#L832)
```
if (!useSocket.url) {
    throw new Error('URL must be defined for nuxtSocket')
  }
```

I think I could change it to: 

```
if (!useSocket.url) {
  consola.info(`URL not defined for socket, defaulting to window.location = ${window.location}`)
}
```

And then downstream, when I make the connect call, I would pass in `window.location` (which is a JSON object containing the full url, port, path, etc. The "path" may be treated as "path" or namespace I believe)

I think this will work but I have test it.

**Comment by jd1378** [comment]
I took a look at what [socket.io-client does with window.location](https://github.com/socketio/socket.io-client/blob/3020e455ab9a81341722e6c1e6cd8ef6b4b0ea28/lib/url.js#L28)
I don't think you need anything to do with path or other things in it
Also now looking at socket.io-client, I guess you don't support relative url as well
why not pass url as is (even undefined) and let the socket.io-client handle it ?

**Comment by richardeschloss** [comment]
Ok, what I'm finding is...if URL is not defined, but `window.location` is used by default, the namespaces won't be used. 

For example, say the `window.location` is: "http://localhost:3000/examples" and a socket.io-client wants to connect, if the full url (string) is passed, then "examples" will be treated like a namespace, but if no url is provided, the full `window.location` will be used by default and a server waiting for connection `io.of('/examples').on('connection', ...)` will never see the connection, but `io.on('connection', ...)` will see the connection.

**Comment by richardeschloss** [comment]
Branch [issue/93](https://github.com/richardeschloss/nuxt-socket-io/tree/issue/93) pushed. Can you please let me know if the [plugin](https://github.com/richardeschloss/nuxt-socket-io/blob/issue/93/io/plugin.js) there does what you expect? I think it will work

**Comment by jd1378** [comment]
Sorry about late reply
I do use namespaces in my app, so I can't really stop using the channel

I've been busy with a bug , where when you set url to '/' then use `channel` inside $nuxtSocket instead of config, it would use the channel as domain name, so that was why i thought nuxt-socket-io doesn't support relative urls while it does, thus I created an issue to omit the url altogether to achieve same result as using '/' as url.

**Comment by richardeschloss** [comment]
I think you'd want to use "path" as the relative url. I thought you had it working in #73 ? 

At any rate, I just updated the branch, and I simplified the connect method. Check out [plugin#L874](https://github.com/richardeschloss/nuxt-socket-io/blob/issue/93/io/plugin.js#L874) in that branch. You can try hardcoding the connect opts there and let me know what ends up working. I think we're pretty close.  If you copy and paste my plugin.js file into your node_modules folder, it should help troubleshoot.

```
socket = io(connectOpts) // L874: update connectOpts here manually...
```

**Comment by jd1378** [comment]
I did wanted to use path, but that was solved in that issue, passing 'path' option worked well,
what i wanted to do now was stop hardcoding my domain address so I don't need to detect production env and change the url based on that

**Comment by jd1378** [comment]
So, first of all , sorry about saying some nonsense in my last comments (I had forgotten about a lot of stuff , so i read the documents again and realized its not possible to set channel in nuxt.config.js anyway )
so I copied your plugin file over, tried, didn't worked because the channel was ignored as you said, so i passed the channel to socket.io when url was not set and problem solved, but ...

Overall I'm a bit confused about the nuxt-socket-io usage (and maybe others too)
It would be kind of you if you explain these:

- Are namespaces of nuxt-socket-io same as namespaces of socket.io server ?
- If not, is there any need to use 'channel' property to connect to a namespace instead of just passing the defined url (or undefined) to socket.io and let it handle relative urls or absolute ones, queries and namespace connection where needed?
- If yes, how would defined namespaces play along with the channel property being passed to $nuxtSocket ?
- does the vuex defined rules inside config respond to emitted events inside all of the defined namespaces ?
- if not, is there any support for adding vuex for each namespace config ?

**Comment by richardeschloss** [comment]
I think it would be some combination of `window.location.origin` and the path you use for your socket.io? I think you'd still want to use "channel" for your namespaces.

So, if you're domain was: 
- https://www.example.com --> https://www.example.com/your/ws/api

`window.location.origin` would be "https://www.example.com"

```
const wsApi = '/your/ws/api`
const channel = '/namespace1'
const url = window.location.origin + channel
const socket = io(url, { path: wsApi })
```

**Comment by jd1378** [comment]
yeah, you don't even need to build the url yourself , you can just pass the channel to socket io and it does the thing you are mentioning

**Comment by jd1378** [comment]
also I really appreciate if you answer the questions, it would help a lot

**Comment by richardeschloss** [comment]
oh yeah, under the hood, socket.io can do that. If you provide just the channel, it will know to use window.location

**Comment by jd1378** [comment]
Sorry i think you missed my comment here https://github.com/richardeschloss/nuxt-socket-io/issues/93#issuecomment-609553749 because we submitted at the same time back then, i meant the questions there

**Comment by richardeschloss** [comment]
I'll try to answer your questions here, in bold: 

- Are namespaces of nuxt-socket-io same as namespaces of socket.io server ?
**A: yes, "channel" is the same thing as "namespace". 

- If not, is there any need to use 'channel' property to connect to a namespace instead of just passing the defined url (or undefined) to socket.io and let it handle relative urls or absolute ones, queries and namespace connection where needed?
**A: it seems like the channel should still be used for your defined namespace, but a new option "apiPath" would have to be used to specify the socket.io api relative path**
- If yes, how would defined namespaces play along with the channel property being passed to $nuxtSocket ?
** Channel property is the namespace, and it's probably best for that. It would probably be more appropriate for `apiPath` to be an option to specify start of socket.io path: (I'm surprised the `path` isn't working)**
```
apiPath = '/your/ws/api` // arg passed in 
const channel = '/namespace1' // your namespace
const url = apiPath + channel
const socket = io(url, connectOpts) // here, url would be relative path, socket.io should know the domain
```
- does the vuex defined rules inside config respond to emitted events inside all of the defined namespaces ?
** A:  Each socket client connects to a given namespace and each client will listen for the events defined in vuex options (in config), but within the namespace. The plugin won't allow duplicate vuex listeners for a given socket (name/url combination). It'll be the first client that connects that will have it's events go to vuex. However, when that client's page gets destroyed, the vuex listeners will be removed and the next client to connect will have his events listened to. **
- if not, is there any support for adding vuex for each namespace config ?
** A: it's an interesting thought, but I think listeners inside each namespace config allows for cleaner and scoped design. But, it's doable in the way that vuex opts supports mapping for events. so the same event name can be mapped based on the namespace that produced it. that makes life a heck of lot easier.

**Comment by richardeschloss** [comment]
And, can I just double check. When you 'path' doesn't work, did you try this?
```
connectOpts.path = path // <-- assign apiPath here
socket = io(channel, connectOpts) // <-- channel...make your namespace
```

Also, just to double-check your connection, is connection succeeding if you do:

```
// io *server*
io.on('connection', (socket) => {
  console.log('do you see me? socket connected to server')
})

io.of('/your/namespace').on('connection', (socket) => {
  console.log('do you see me? socket connected to namespace')
})
```

Does it work? Or still, does path not work? Do any of those log statements get printed?

**Comment by jd1378** [comment]
path did work , i think i did say multiple times that it did indeed work when given inside $nuxtSocket() options

**Comment by jd1378** [comment]
and i did also do the log thing to confirm the connection and namespaces

**Comment by jd1378** [comment]
about my questions, i think they were not clear enough
my first question was: is [this](https://github.com/richardeschloss/nuxt-socket-io#configuration-namespaces-) same as [this](https://socket.io/docs/server-api/#Namespace) ?

**Comment by richardeschloss** [comment]
technically those two things are different. one is the namespace config (in the plugin), and the other is the namespace api and state. I'll come out with a pull request soon, I think I know the change needed here.

**Comment by jd1378** [comment]
So what I'm saying is if the namespace config (in the plugin) means different than the namespace of socket.io (which it is it seems) , you should state that inside readme to prevent confusion.
It is somewhat ambiguous that what namespace of your plugin refers to, is it vuex's ? is it socket.io's ? is it something of this plugin's definition ? it would help to distinguish between them

**Comment by jd1378** [comment]
I really apologize for my lack of understanding, I think I got what is what, I'm really sorry
I had to go through docs a few more times to understand what it refers to

**Comment by richardeschloss** [comment]
I think maybe a link to socket.io's namespaces would be sufficient. The wording is: 
"Each socket set can have its own configuration of [namespaces](https://socket.io/docs/server-api/#Namespace) and each namespace can now have emitters, listeners, and emitbacks."
^ link to be added.

This "namespace" config talks about how one would configure emitters and listeners for a given namespace, which is what is described in the link. But, the client would really only care about the namespace's *name*. The link refers to namespaces api and state on the server. Even though Nuxt can be server-side code, the plugin uses socket io client only.

**Comment by jd1378** [comment]
Thanks a lot for taking your time to make this plugin better, and thanks again for explaining things patiently, it means a lot
I'll be waiting for release of this feature (not using url) , keep up 👍

**Comment by richardeschloss** [comment]
[PR](https://github.com/richardeschloss/nuxt-socket-io/pull/94)
