### ISSUE TITLE
Question: How to Pass in Request Headers to Nuxt Socket Instance?

### ISSUE THREAD

**Issue by MohammedBashiru** [richardeschloss/nuxt-socket-io#96]
Hi, how can I pass in extra headers.
I tried 

```
this.socket = this.$nuxtSocket({
  extraHeaders: { 
    Authorization: `Bearer ${cookie}` 
  }
}).on("unauthorized", (error) => {
  console.log("error", error);
});
```

but on the server when I check `handshake.headers`. I can't find Authorization. Can you help please?

**Comment by richardeschloss** [comment]
I'll look into it right now

**Comment by richardeschloss** [comment]
Hi, ok, the solution is pretty straightforward, with a caveat to be explained below:
```
this.socket = this.$nuxtSocket({
  transportOptions: { 
    polling: {
      extraHeaders: { // <-- extraHeaders gets nested under transportOptions.polling
        Authorization: `Bearer ${cookie}`
      }
    }
  }
})
```

Then on server side, you can see the value here:
```
io.on('connection', (socket) => {
  const { Authorization } = socket.handshake.headers 
  console.log('Authorization: ', Authorization) //  Bearer [cookie]
})
```
Caveat:
Custom headers only work with "polling" as the transport :(. I hope that's ok. More info [here](https://socket.io/docs/client-api/#With-extraHeaders)
